package org.volunteertech.pledges.localisation.dao;
import java.util.Date;
import java.math.BigDecimal;

/**
 * The model to hold localisation messages
 * This class has been generated by the XSLT processor from the metadata and represents the
 * DataBase access handler for the MessageResource entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public class MessageResourceHistory
{
	/** Hibernate Id */
	private Long id;
	
	/** id from the parent table for which this represents an historic record **/
	private Long messageResourceID;
	 
    
    /** the message key used to lookup the message */
    private String messageKey;
	
    /** the Locale */
    private String locale;
	
    /** the Locale */
    private Long localeReferenceId;
	
    /** the Message in this locale */
    private String message;
	     
    
    /** The user ID of the person that originally created the underlying record **/
    private Long createdByID;

    /** The user ID of the person that last updated the underlying record **/
    private Long updatedByID;

    /** The date that the underlying record was created DD/MM/YYYY-HH:MM format **/
    private Date dateCreated;

    /** The date that the underlying record was last updated DD/MM/YYYY-HH:MM format **/
    private Date dateUpdated;
    

    /**
     * Default Constructor for the MessageResource bean
     */
    public MessageResourceHistory()
    {
    	messageResourceID = new Long(0);
    	messageKey = "";
		locale = "";
		localeReferenceId = new Long("0");
		message = "";
		
    }
    
    /*
     * Returns the Id for the underlying database table record
     */
	public Long getId()
	{
        return id;
    }

	/**
	 * We usually do not manipulate the identity of an object, hence the setter method should be private.
	 */
	@SuppressWarnings("unused")
    private void setId(Long id)
    {
        this.id = id;
    }    


    /*
     * Returns the MessageResourceID for the parent record
     */
	public Long getMessageResourceID()
	{
        return messageResourceID;
    }

	/**
	 * We usually do not manipulate the identity of an object, hence the setter method should be private.
	 */
	@SuppressWarnings("unused")
    private void setMessageResourceID(Long messageResourceID)
    {
        this.messageResourceID = messageResourceID;
    }    

    

    
    
    /**
     * Sets the message key used to lookup the message
     * @param messageKey is the message key used to lookup the message
     */
    public void setMessageKey(String messageKey)
    {
      this.messageKey = messageKey;
    }

    /**
     * Returns the message key used to lookup the message
     * @return the message key used to lookup the message
     */
    public String getMessageKey()
    {
      return messageKey;
    }

    
    /**
     * Sets the Locale
     * @param locale is the Locale
     */
    public void setLocale(String locale)
    {
      this.locale = locale;
    }

    /**
     * Returns the Locale
     * @return the Locale
     */
    public String getLocale()
    {
      return locale;
    }

    
    /**
     * Sets the Locale
     * @param localeReferenceId is the Locale
     */
    public void setLocaleReferenceId(Long localeReferenceId)
    {
      this.localeReferenceId = localeReferenceId;
    }

    /**
     * Returns the Locale
     * @return the Locale
     */
    public Long getLocaleReferenceId()
    {
      return localeReferenceId;
    }

    
    /**
     * Sets the Message in this locale
     * @param message is the Message in this locale
     */
    public void setMessage(String message)
    {
      this.message = message;
    }

    /**
     * Returns the Message in this locale
     * @return the Message in this locale
     */
    public String getMessage()
    {
      return message;
    }


    /**
     * sets the ID of the user that created the underlying record
     */
    public void setCreatedByID(Long createdByID)
    {
        this.createdByID = createdByID;
    }


    /**
     * gets the ID of the user that created the underlying record
     */
    public Long getCreatedByID()
    {
        return createdByID;
    }
     
     
    /**
     * sets the ID of the user that last updated the underlying record
     */
    public void setUpdatedByID(Long updatedByID)
    {
        this.updatedByID = updatedByID;
    }
     
     
    /**
     * gets the ID of the user that last updated the underlying record
     */
    public Long getUpdatedByID()
    {
        return updatedByID;
    }


    /**
     * sets the date that the underlying record was first created as a <code>java.util.Date</code> object
     */
    public void setDateCreated(Date dateCreated)
    {
        this.dateCreated = dateCreated;
    }

     
    /**
     * Gets the date that the underlying record was first created as a <code>java.util.Date</code> object
     */
    public Date getDateCreated()
    {
        return dateCreated;
    }

    /**
     * sets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     */
    public void setDateUpdated(Date dateUpdated)
    {
        this.dateUpdated = dateUpdated;
    }


    
    /**
     * Gets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     */
    public Date getDateUpdated()
    {
        return dateUpdated;
    }
    
     
}
    
    
    

