// default package
// Generated Jul 14, 2016 11:10:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Applicationuserhistory generated by hbm2java
 */
@Entity
@Table(name = "APPLICATIONUSERHISTORY", catalog = "netgrains")
public class Applicationuserhistory implements java.io.Serializable {

	private Long applicationuserhistoryid;
	private Long applicationuserid;
	private String username;
	private String password;
	private Boolean enabled;
	private Long createdbyid;
	private Long updatedbyid;
	private Date datecreated;
	private Date dateupdated;

	public Applicationuserhistory() {
	}

	public Applicationuserhistory(Long applicationuserid, String username, String password, Boolean enabled,
			Long createdbyid, Long updatedbyid, Date datecreated, Date dateupdated) {
		this.applicationuserid = applicationuserid;
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.createdbyid = createdbyid;
		this.updatedbyid = updatedbyid;
		this.datecreated = datecreated;
		this.dateupdated = dateupdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "APPLICATIONUSERHISTORYID", unique = true, nullable = false)
	public Long getApplicationuserhistoryid() {
		return this.applicationuserhistoryid;
	}

	public void setApplicationuserhistoryid(Long applicationuserhistoryid) {
		this.applicationuserhistoryid = applicationuserhistoryid;
	}

	@Column(name = "APPLICATIONUSERID")
	public Long getApplicationuserid() {
		return this.applicationuserid;
	}

	public void setApplicationuserid(Long applicationuserid) {
		this.applicationuserid = applicationuserid;
	}

	@Column(name = "USERNAME", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ENABLED")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "CREATEDBYID")
	public Long getCreatedbyid() {
		return this.createdbyid;
	}

	public void setCreatedbyid(Long createdbyid) {
		this.createdbyid = createdbyid;
	}

	@Column(name = "UPDATEDBYID")
	public Long getUpdatedbyid() {
		return this.updatedbyid;
	}

	public void setUpdatedbyid(Long updatedbyid) {
		this.updatedbyid = updatedbyid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATECREATED", length = 19)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEUPDATED", length = 19)
	public Date getDateupdated() {
		return this.dateupdated;
	}

	public void setDateupdated(Date dateupdated) {
		this.dateupdated = dateupdated;
	}

}
