// default package
// Generated Jul 14, 2016 11:10:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Applicationuser generated by hbm2java
 */
@Entity
@Table(name = "APPLICATIONUSER", catalog = "netgrains", uniqueConstraints = {
		@UniqueConstraint(columnNames = "USERNAME"), @UniqueConstraint(columnNames = "applicationUserDetails") })
public class Applicationuser implements java.io.Serializable {

	private Long applicationuserid;
	private String username;
	private String password;
	private Boolean enabled;
	private Long applicationUserDetails;
	private Long createdbyid;
	private Long updatedbyid;
	private Date datecreated;
	private Date dateupdated;

	public Applicationuser() {
	}

	public Applicationuser(String password) {
		this.password = password;
	}

	public Applicationuser(String username, String password, Boolean enabled, Long applicationUserDetails,
			Long createdbyid, Long updatedbyid, Date datecreated, Date dateupdated) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.applicationUserDetails = applicationUserDetails;
		this.createdbyid = createdbyid;
		this.updatedbyid = updatedbyid;
		this.datecreated = datecreated;
		this.dateupdated = dateupdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "APPLICATIONUSERID", unique = true, nullable = false)
	public Long getApplicationuserid() {
		return this.applicationuserid;
	}

	public void setApplicationuserid(Long applicationuserid) {
		this.applicationuserid = applicationuserid;
	}

	@Column(name = "USERNAME", unique = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ENABLED")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "applicationUserDetails", unique = true)
	public Long getApplicationUserDetails() {
		return this.applicationUserDetails;
	}

	public void setApplicationUserDetails(Long applicationUserDetails) {
		this.applicationUserDetails = applicationUserDetails;
	}

	@Column(name = "CREATEDBYID")
	public Long getCreatedbyid() {
		return this.createdbyid;
	}

	public void setCreatedbyid(Long createdbyid) {
		this.createdbyid = createdbyid;
	}

	@Column(name = "UPDATEDBYID")
	public Long getUpdatedbyid() {
		return this.updatedbyid;
	}

	public void setUpdatedbyid(Long updatedbyid) {
		this.updatedbyid = updatedbyid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATECREATED", length = 19)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEUPDATED", length = 19)
	public Date getDateupdated() {
		return this.dateupdated;
	}

	public void setDateupdated(Date dateupdated) {
		this.dateupdated = dateupdated;
	}

}
