// default package
// Generated Jul 14, 2016 11:10:17 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReferencecategoryReference generated by hbm2java
 */
@Entity
@Table(name = "REFERENCECATEGORY_REFERENCE", catalog = "netgrains")
public class ReferencecategoryReference implements java.io.Serializable {

	private ReferencecategoryReferenceId id;

	public ReferencecategoryReference() {
	}

	public ReferencecategoryReference(ReferencecategoryReferenceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "referencecategoryid", column = @Column(name = "REFERENCECATEGORYID", nullable = false)),
			@AttributeOverride(name = "referenceid", column = @Column(name = "REFERENCEID", nullable = false)) })
	public ReferencecategoryReferenceId getId() {
		return this.id;
	}

	public void setId(ReferencecategoryReferenceId id) {
		this.id = id;
	}

}
