// default package
// Generated Jul 14, 2016 11:10:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registerofpledgeshistory generated by hbm2java
 */
@Entity
@Table(name = "REGISTEROFPLEDGESHISTORY", catalog = "netgrains")
public class Registerofpledgeshistory implements java.io.Serializable {

	private Long registerofpledgeshistoryid;
	private Long registerofpledgesid;
	private Long createdbyid;
	private Long updatedbyid;
	private Date datecreated;
	private Date dateupdated;

	public Registerofpledgeshistory() {
	}

	public Registerofpledgeshistory(Long registerofpledgesid, Long createdbyid, Long updatedbyid, Date datecreated,
			Date dateupdated) {
		this.registerofpledgesid = registerofpledgesid;
		this.createdbyid = createdbyid;
		this.updatedbyid = updatedbyid;
		this.datecreated = datecreated;
		this.dateupdated = dateupdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REGISTEROFPLEDGESHISTORYID", unique = true, nullable = false)
	public Long getRegisterofpledgeshistoryid() {
		return this.registerofpledgeshistoryid;
	}

	public void setRegisterofpledgeshistoryid(Long registerofpledgeshistoryid) {
		this.registerofpledgeshistoryid = registerofpledgeshistoryid;
	}

	@Column(name = "REGISTEROFPLEDGESID")
	public Long getRegisterofpledgesid() {
		return this.registerofpledgesid;
	}

	public void setRegisterofpledgesid(Long registerofpledgesid) {
		this.registerofpledgesid = registerofpledgesid;
	}

	@Column(name = "CREATEDBYID")
	public Long getCreatedbyid() {
		return this.createdbyid;
	}

	public void setCreatedbyid(Long createdbyid) {
		this.createdbyid = createdbyid;
	}

	@Column(name = "UPDATEDBYID")
	public Long getUpdatedbyid() {
		return this.updatedbyid;
	}

	public void setUpdatedbyid(Long updatedbyid) {
		this.updatedbyid = updatedbyid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATECREATED", length = 19)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEUPDATED", length = 19)
	public Date getDateupdated() {
		return this.dateupdated;
	}

	public void setDateupdated(Date dateupdated) {
		this.dateupdated = dateupdated;
	}

}
