package org.volunteertech.pledges.reference.dao;
import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import java.util.HashSet;
import java.math.BigDecimal;


import org.volunteertech.pledges.reference.dao.ReferenceCategory;




/**
 * The reference screen is used to add/edit new/existing reference entries. The reference entries are used to populate dropdowns where a group of reference entries with a common column-value can be associated with a dropdown.
 * This Interface has been generated by the XSLT processor from the metadata and represents the
 * DataBase access handler interface for the Reference entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public interface Reference extends Serializable { 

    public enum CurrentMode{
    	ADD,UPDATE,LOCALIZE;
    	
    	public String toString(){
    		switch(this){
    			case ADD: return "ADD";
    			case UPDATE: return "UPDATE";
    			case LOCALIZE: return "LOCALIZE";
    			default: return "UNKNOWN";
    		}	
    	}
    }
    	
    /**
     * Returns the Id for the underlying database table record
     * @return the Id for the underlying database table record
     */
	public Long getId();
	
    /**
     * Sets the Id. This allows front-end forms to bind the id property.
     * @param id the Id for the underlying database table record.
     */
	public void setId(Long id);
	
    /**
     * Returns the parentObjectId when this object has been populated via a restful webservice JSON mapping
     * @return the parentObjectId when this object has been populated via a restful webservice JSON mapping
     */
	public Long getParentObjectId();
	
    /**
     * Sets the parentObjectId. This allows restful web services to bind the parentId property when adding a new record.
     * @param parentObjectId allows restful web services to bind the parentId property when adding a new record.
     */
	public void setParentObjectId(Long parentObjectId);
    
    
    /**
     * Sets the reference type grouping for the entity
     * @param refType is the reference type grouping for the entity
     */
    public void setRefType(String refType);

    /**
     * Returns the reference type grouping for the entity
     * @return the reference type grouping for the entity
     */
    public String getRefType();
    
    
    /**
     * Sets the unique reference description within the reference type group
     * @param refDesc is the unique reference description within the reference type group
     */
    public void setRefDesc(String refDesc);

    /**
     * Returns the unique reference description within the reference type group
     * @return the unique reference description within the reference type group
     */
    public String getRefDesc();
    
    
    /**
     * Sets the column-value that allows an entry to be linked to a parent entity
     * @param parentId is the column-value that allows an entry to be linked to a parent entity
     */
    public void setParentId(Long parentId);

    /**
     * Returns the column-value that allows an entry to be linked to a parent entity
     * @return the column-value that allows an entry to be linked to a parent entity
     */
    public Long getParentId();
    
    
    /**
     * Sets the order in which the reference entity is placed in its column-value group
     * @param refIndex is the order in which the reference entity is placed in its column-value group
     */
    public void setRefIndex(Long refIndex);

    /**
     * Returns the order in which the reference entity is placed in its column-value group
     * @return the order in which the reference entity is placed in its column-value group
     */
    public Long getRefIndex();
    
    
    /**
     * Sets a user friendly description of the reference item
     * @param description is a user friendly description of the reference item
     */
    public void setDescription(String description);

    /**
     * Returns a user friendly description of the reference item
     * @return a user friendly description of the reference item
     */
    public String getDescription();
    
    /**
     * Sets the <code>Set</code> of associated ReferenceCategory mapped as the referenceCategory property
     * @param the <code>Set</code> of associated ReferenceCategory mapped as the referenceCategory property
     */
    public void setReferenceCategory(Set<ReferenceCategory> referenceCategory);

    /**
     * Returns the <code>Set</code> of associated ReferenceCategory mapped as the referenceCategory property
     * @return the <code>Set</code> of associated ReferenceCategory mapped as the referenceCategory property
     */
    public Set<ReferenceCategory>  getReferenceCategory();


  

    /**
     * sets the Id of the user that created the underlying record
     * @param createdByID the Id of the user that created the underlying record
     */
    public void setCreatedByID(Long createdByID);
    
    /**
     * gets the Id of the user that created the underlying record
     * @return the Id of the user that created the underlying record
     */
    public Long getCreatedByID();
         
   	/**
     * sets the Id of the user that last updated the underlying record
     * @param updatedByID the Id of the user that last updated the underlying record
     */
    public void setUpdatedByID(Long updatedByID);
     
    /**
     * gets the Id of the user that last updated the underlying record
     * @return the Id of the user that last updated the underlying record
     */
    public Long getUpdatedByID();

    /**
     * sets the date that the underlying record was first created as a <code>java.util.Date</code> object
     * @param dateCreated the date that the underlying record was first created
     */
    public void setDateCreated(Date dateCreated);

    /**
     * Gets the date that the underlying record was first created as a <code>java.util.Date</code> object
     * @return the date that the underlying record was first created
     */
    public Date getDateCreated();

    /**
     * Sets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     * @param dateUpdated the date that the underlying record was last updated
     */
    public void setDateUpdated(Date dateUpdated);
    
    /**
     * Gets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     * @return the date that the underlying record was last updated
     */
    public Date getDateUpdated();
    
    /**
     * Checks for a newly created entity object
     * @return true if this is a newly created entity object meaning that it has not yet been persisted, otherwise false
     */
	public boolean isNew();
	
	/**
	 * Sets the current mode of use for the entity object;
	 * @param mode a member of the CurrentMode enumeration
	 */
	public void setCurrentMode(CurrentMode mode);

    /**
     * Returns the current mode under which the class instance was loaded
     * @return A member of the CurrentMode Enumeration
     */
	public CurrentMode getCurrentMode();
}
    
    
    

