package org.volunteertech.pledges.accommodationpledge.web;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.SortedMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.Locale;

import org.volunteertech.pledges.accommodationpledge.dao.AccommodationPledge;
import org.volunteertech.pledges.accommodationpledge.dao.AccommodationPledgeImpl;
import org.volunteertech.pledges.accommodationpledge.service.AccommodationPledgeService;
import org.volunteertech.pledges.accommodationpledge.dao.AccommodationPledgeLoadException;
import org.volunteertech.pledges.accommodationpledge.dao.AccommodationPledgeSaveException;
import org.volunteertech.pledges.accommodationpledge.validator.AccommodationPledgeFormValidator;
import org.volunteertech.pledges.main.web.BaseController;
import org.volunteertech.pledges.users.security.SecurityUser;

import org.volunteertech.pledges.reference.ReferenceStore;


import org.volunteertech.pledges.pledge.dao.RegisterOfPledgesImpl;




/**
 * The Accommodation pledge screen is used to add/edit a new/existing pledge of accommodation
 * The Spring AccommodationPledgeRestController to handle restful web service requests.
 * This class has been generated by the XSLT processor from the metadata and represents the
 * the Spring AccommodationPledgeRestController to handle restful web service requests.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">>JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
@RestController
public class AccommodationPledgeRestController extends BaseController
{
	final Logger logger = LoggerFactory.getLogger(AccommodationPledgeRestController.class);
	
	@Autowired
	private ReferenceStore referenceStore;
	
	@Autowired
	private AccommodationPledgeService accommodationPledgeService;
	
	


	/**
	 * Returns a JSON representation of all AccommodationPledge records
	 * @return the JSON representation of all AccommodationPledge.
	 */
	@RequestMapping(value = "/restful/accommodationpledge/list", method = RequestMethod.GET)
	@ResponseBody
    public List<AccommodationPledge> showAllAccommodationPledge(Authentication authentication, Locale locale) {
		logger.info("Inside restful getAccommodationPledge method...");
		List <AccommodationPledge> accommodationPledgeList = null;
		SecurityUser user = (SecurityUser)authentication.getPrincipal();
        Long userId = user.getApplicationUser().getId();		
		
		try{
			// TODO: Needs exception handling policy
	    	accommodationPledgeList = accommodationPledgeService.listAccommodationPledge();
	    	accommodationPledgeList = accommodationPledgeService.translateReferenceValues(accommodationPledgeList, locale);
		}
		catch (Exception ex){
			logger.error("Exception caught !!!!!!!!!!!!!!", ex);
		}		
		
		
    	return accommodationPledgeList;
    }


	
	/**
	 * Returns a JSON representation of the AccommodationPledge record that matches the id parameter
	 * @param id the primary key by which to search
	 * @return the AccommodationPledge with the relevant primary key.
	 */
	@RequestMapping(value = "/restful/accommodationpledge", method = RequestMethod.GET)
	@ResponseBody
    public AccommodationPledge getAccommodationPledge(Authentication authentication, @RequestParam(value="id") String id) {
		logger.info("Inside restful getAccommodationPledge method...");
		AccommodationPledge accommodationPledge = null;
		SecurityUser user = (SecurityUser)authentication.getPrincipal();
        Long userId = user.getApplicationUser().getId();		
		
		try{
			// TODO: Needs exception handling policy
	    	accommodationPledge = accommodationPledgeService.load(new Long(id), userId);
		}
		catch (Exception ex){
			logger.error("Exception caught !!!!!!!!!!!!!!", ex);
		}		
		
		
    	return accommodationPledge;
    }
    
    @RequestMapping(value = "/restful/accommodationpledge/update", method = RequestMethod.POST)
    @ResponseBody
    public List<AccommodationPledge> updateAccommodationPledge(Authentication authentication, @RequestBody AccommodationPledge accommodationPledge) {
        logger.debug("In the updateAccommodationPledge controller and got Id: " + accommodationPledge.getId());

		SecurityUser user = (SecurityUser)authentication.getPrincipal();
        Long userId = user.getApplicationUser().getId();
        
		try{
			// TODO needs security update
			accommodationPledgeService.storeAccommodationPledge(accommodationPledge, userId);
		}
		catch (Exception ex){
		// TODO needs custom exception handling
		logger.error("Exception caught !!!!!!!!!!!!!!", ex);
		}
    	List<AccommodationPledge> accommodationPledgeList = accommodationPledgeService.listAccommodationPledge();
        
        return accommodationPledgeList;
    }
    
    
    @RequestMapping(value = "/restful/accommodationpledge/new", method = RequestMethod.POST)
    @ResponseBody
    public List<AccommodationPledge> addAccommodationPledge(Authentication authentication, @RequestBody AccommodationPledge accommodationPledge) {
        logger.debug("In the addAccommodationPledge controller and got Id: " + accommodationPledge.getId());
        SecurityUser user = (SecurityUser)authentication.getPrincipal();
        Long userId = user.getApplicationUser().getId();

		try{
			// TODO needs security update
			accommodationPledgeService.storeAccommodationPledge(accommodationPledge, userId);
		}
		catch (Exception ex){
		// TODO needs custom exception handling
		logger.error("Exception caught !!!!!!!!!!!!!!", ex);
		}
    	List<AccommodationPledge> accommodationPledgeList = accommodationPledgeService.listAccommodationPledge();
        
        return accommodationPledgeList;
    }
    
    
    
	/**
	 * Returns a JSON representation of a list of AccommodationPledge entries that match the registerOfPledgesId
	 * parameter.
	 * @param registerOfPledgesId by which to filter.
	 * @return a <code>List<AccommodationPledge></code> containing the AccommodationPledge
	 * entries that match the registerOfPledgesId
	 */
	@RequestMapping(value = "/restful/accommodationpledgebyregisterofpledgeslist", method = RequestMethod.GET)
    public List<AccommodationPledge> getAccommodationPledgeByRegisterOfPledgesId(@RequestParam(value="registerOfPledgesId") String registerOfPledgesId) {
		logger.info("Inside getAccommodationPledgeByRegisterOfPledgesId() method...");
		
    	List<AccommodationPledge> accommodationPledgeList = accommodationPledgeService.getAccommodationPledgeBo().getAccommodationPledgeDao().listAccommodationPledgeByRegisterOfPledgesId(new Long(registerOfPledgesId));
		
    	return accommodationPledgeList;
    }
  
}
