package org.volunteertech.pledges.servicepledge.dao;
import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import java.util.HashSet;
import java.math.BigDecimal;


import org.volunteertech.pledges.pledge.dao.RegisterOfPledges;




/**
 * The pledge services screen is used to add/edit a new/existing pledge of services
 * This Interface has been generated by the XSLT processor from the metadata and represents the
 * DataBase access handler interface for the ServicePledge entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public interface ServicePledge extends Serializable { 

    public enum CurrentMode{
    	ADD,UPDATE,LOCALIZE;
    	
    	public String toString(){
    		switch(this){
    			case ADD: return "ADD";
    			case UPDATE: return "UPDATE";
    			case LOCALIZE: return "LOCALIZE";
    			default: return "UNKNOWN";
    		}	
    	}
    }
    	
    /**
     * Returns the Id for the underlying database table record
     * @return the Id for the underlying database table record
     */
	public Long getId();
	
    /**
     * Sets the Id. This allows front-end forms to bind the id property.
     * @param id the Id for the underlying database table record.
     */
	public void setId(Long id);
	
    /**
     * Returns the parentObjectId when this object has been populated via a restful webservice JSON mapping
     * @return the parentObjectId when this object has been populated via a restful webservice JSON mapping
     */
	public Long getParentObjectId();
	
    /**
     * Sets the parentObjectId. This allows restful web services to bind the parentId property when adding a new record.
     * @param parentObjectId allows restful web services to bind the parentId property when adding a new record.
     */
	public void setParentObjectId(Long parentObjectId);
    
    
    /**
     * Sets the address type that has been chosen by the user
     * @param pledgeServiceLevelOne is the address type
     */
    public void setPledgeServiceLevelOne(Long pledgeServiceLevelOne);

    /**
     * Returns the address type that has been chosen by the user or saved in the database
     * @return the address type
     */
    public Long getPledgeServiceLevelOne();
    
    /**
     * Sets the translated reference mapping for the address type that has been chosen by the user
     * @param the translated reference mapping for pledgeServiceLevelOne is the address type
     */
    public void setPledgeServiceLevelOneReferenceTranslation(String pledgeServiceLevelOneReferenceTranslation);

    /**
     * Returns the translated reference mapping for the address type that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the address type
     */
    public String getPledgeServiceLevelOneReferenceTranslation();
      
    
    /**
     * Sets the address type that has been chosen by the user
     * @param pledgeServiceLevelTwo is the address type
     */
    public void setPledgeServiceLevelTwo(Long pledgeServiceLevelTwo);

    /**
     * Returns the address type that has been chosen by the user or saved in the database
     * @return the address type
     */
    public Long getPledgeServiceLevelTwo();
    
    /**
     * Sets the translated reference mapping for the address type that has been chosen by the user
     * @param the translated reference mapping for pledgeServiceLevelTwo is the address type
     */
    public void setPledgeServiceLevelTwoReferenceTranslation(String pledgeServiceLevelTwoReferenceTranslation);

    /**
     * Returns the translated reference mapping for the address type that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the address type
     */
    public String getPledgeServiceLevelTwoReferenceTranslation();
      
    
    /**
     * Sets the address type that has been chosen by the user
     * @param pledgeServiceLevelThree is the address type
     */
    public void setPledgeServiceLevelThree(Long pledgeServiceLevelThree);

    /**
     * Returns the address type that has been chosen by the user or saved in the database
     * @return the address type
     */
    public Long getPledgeServiceLevelThree();
    
    /**
     * Sets the translated reference mapping for the address type that has been chosen by the user
     * @param the translated reference mapping for pledgeServiceLevelThree is the address type
     */
    public void setPledgeServiceLevelThreeReferenceTranslation(String pledgeServiceLevelThreeReferenceTranslation);

    /**
     * Returns the translated reference mapping for the address type that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the address type
     */
    public String getPledgeServiceLevelThreeReferenceTranslation();
      
    
    /**
     * Sets the participant comments
     * @param additionalInformation is the participant comments
     */
    public void setAdditionalInformation(String additionalInformation);

    /**
     * Returns the participant comments
     * @return the participant comments
     */
    public String getAdditionalInformation();
    
    
    /**
     * Sets the participant comments
     * @param pledgeServiceQualification is the participant comments
     */
    public void setPledgeServiceQualification(String pledgeServiceQualification);

    /**
     * Returns the participant comments
     * @return the participant comments
     */
    public String getPledgeServiceQualification();
    
    
    /**
     * Sets the participant date of birth
     * @param pledgeServiceDateAvailable is the participant date of birth
     */
    public void setPledgeServiceDateAvailable(Date pledgeServiceDateAvailable);

    /**
     * Returns the participant date of birth
     * @return the participant date of birth
     */
    public Date getPledgeServiceDateAvailable();
    
    
    /**
     * Sets the address type that has been chosen by the user
     * @param pledgeServiceHoursPerWeek is the address type
     */
    public void setPledgeServiceHoursPerWeek(Long pledgeServiceHoursPerWeek);

    /**
     * Returns the address type that has been chosen by the user or saved in the database
     * @return the address type
     */
    public Long getPledgeServiceHoursPerWeek();
    
    /**
     * Sets the translated reference mapping for the address type that has been chosen by the user
     * @param the translated reference mapping for pledgeServiceHoursPerWeek is the address type
     */
    public void setPledgeServiceHoursPerWeekReferenceTranslation(String pledgeServiceHoursPerWeekReferenceTranslation);

    /**
     * Returns the translated reference mapping for the address type that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the address type
     */
    public String getPledgeServiceHoursPerWeekReferenceTranslation();
      
    /**
     * Sets the associated RegisterOfPledges mapped as the registerOfPledges property
     * @param the associated RegisterOfPledges mapped as the registerOfPledges property
     */
    public void setRegisterOfPledges(RegisterOfPledges registerOfPledges);

    /**
     * Returns the associated RegisterOfPledges mapped as the registerOfPledges property
     * @return the associated RegisterOfPledges mapped as the registerOfPledges property
     */
    public RegisterOfPledges getRegisterOfPledges();
  

    /**
     * sets the Id of the user that created the underlying record
     * @param createdByID the Id of the user that created the underlying record
     */
    public void setCreatedByID(Long createdByID);
    
    /**
     * gets the Id of the user that created the underlying record
     * @return the Id of the user that created the underlying record
     */
    public Long getCreatedByID();
         
   	/**
     * sets the Id of the user that last updated the underlying record
     * @param updatedByID the Id of the user that last updated the underlying record
     */
    public void setUpdatedByID(Long updatedByID);
     
    /**
     * gets the Id of the user that last updated the underlying record
     * @return the Id of the user that last updated the underlying record
     */
    public Long getUpdatedByID();

    /**
     * sets the date that the underlying record was first created as a <code>java.util.Date</code> object
     * @param dateCreated the date that the underlying record was first created
     */
    public void setDateCreated(Date dateCreated);

    /**
     * Gets the date that the underlying record was first created as a <code>java.util.Date</code> object
     * @return the date that the underlying record was first created
     */
    public Date getDateCreated();

    /**
     * Sets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     * @param dateUpdated the date that the underlying record was last updated
     */
    public void setDateUpdated(Date dateUpdated);
    
    /**
     * Gets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     * @return the date that the underlying record was last updated
     */
    public Date getDateUpdated();
    
    /**
     * Checks for a newly created entity object
     * @return true if this is a newly created entity object meaning that it has not yet been persisted, otherwise false
     */
	public boolean isNew();
	
	/**
	 * Sets the current mode of use for the entity object;
	 * @param mode a member of the CurrentMode enumeration
	 */
	public void setCurrentMode(CurrentMode mode);

    /**
     * Returns the current mode under which the class instance was loaded
     * @return A member of the CurrentMode Enumeration
     */
	public CurrentMode getCurrentMode();
}
    
    
    

