package org.volunteertech.pledges.pledge.view;

import org.volunteertech.pledges.pledge.dao.RegisterOfPledgesImpl;
import java.io.Serializable;


import org.volunteertech.pledges.users.dao.ApplicationUserDetails;

import org.volunteertech.pledges.accommodationpledge.dao.AccommodationPledge;

import org.volunteertech.pledges.servicepledge.dao.ServicePledge;

import org.volunteertech.pledges.goodspledge.dao.GoodsPledge;




/**
 * The register of pledges screen is used to add/edit new/existing pledges
 * The RegisterOfPledgesTranslationBacking Bean supports the localisation of the RegisterOfPledges Screen
 * This class has been generated by the XSLT processor from the metadata and represents the
 * DataBase access handler for the RegisterOfPledges entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public class RegisterOfPledgesTranslationBackingBeanImpl extends RegisterOfPledgesImpl implements RegisterOfPledgesTranslationBackingBean, Serializable { 

    private static final long serialVersionUID = 1L;
    
    /** The identifier for the Pledge Profile view */
    public static final Long VIEW_ID = new Long(2);
    
    /** The mapping key for the page title as displayed in the browser tab */
    public static String REGISTEROFPLEDGES_TITLE_MAPPING_KEY = "registerofpledges.form.title";
    
    /** The mapping key for the page header text as displayed at the top of the page */
    public static String REGISTEROFPLEDGES_HEADER_MAPPING_KEY = "registerofpledges.form.header";
    
    /** The mapping key for the form sub header */
    public static String REGISTEROFPLEDGES_SUBHEADER_MAPPING_KEY = "registerofpledges.form.subheader";
    
    
	/** The message resource mapping for the message that represents the contactInformationInstructions property */  
	public static final String CONTACTINFORMATIONINSTRUCTIONS_MESSAGE_MAPPING_KEY = "frmRegisterOfPledgesContactInformationInstructionsMessage";
  
	/** The message resource mapping for the Label attached to the contactInformationInstructions property */  
	public static final String CONTACTINFORMATIONINSTRUCTIONS_LABEL_MAPPING_KEY = "frmRegisterOfPledgesContactInformationInstructionsLabel";
	
	/** The message resource mapping for the place holder attached to the contactInformationInstructions property */  
	public static final String CONTACTINFORMATIONINSTRUCTIONS_PLACEHOLDER_MAPPING_KEY = "frmRegisterOfPledgesContactInformationInstructionsPlaceHolder";

	/** The message resource mapping for the help text attached to the contactInformationInstructions property */  
	public static final String CONTACTINFORMATIONINSTRUCTIONS_HELPBLOCK_MAPPING_KEY = "frmRegisterOfPledgesContactInformationInstructionsHelpBlock";

	/** The message resource mapping for the message that represents the accommodationPledgeInstructions property */  
	public static final String ACCOMMODATIONPLEDGEINSTRUCTIONS_MESSAGE_MAPPING_KEY = "frmRegisterOfPledgesAccommodationPledgeInstructionsMessage";
  
	/** The message resource mapping for the Label attached to the accommodationPledgeInstructions property */  
	public static final String ACCOMMODATIONPLEDGEINSTRUCTIONS_LABEL_MAPPING_KEY = "frmRegisterOfPledgesAccommodationPledgeInstructionsLabel";
	
	/** The message resource mapping for the place holder attached to the accommodationPledgeInstructions property */  
	public static final String ACCOMMODATIONPLEDGEINSTRUCTIONS_PLACEHOLDER_MAPPING_KEY = "frmRegisterOfPledgesAccommodationPledgeInstructionsPlaceHolder";

	/** The message resource mapping for the help text attached to the accommodationPledgeInstructions property */  
	public static final String ACCOMMODATIONPLEDGEINSTRUCTIONS_HELPBLOCK_MAPPING_KEY = "frmRegisterOfPledgesAccommodationPledgeInstructionsHelpBlock";

	/** The message resource mapping for the message that represents the servicePledgeInstructions property */  
	public static final String SERVICEPLEDGEINSTRUCTIONS_MESSAGE_MAPPING_KEY = "frmRegisterOfPledgesServicePledgeInstructionsMessage";
  
	/** The message resource mapping for the Label attached to the servicePledgeInstructions property */  
	public static final String SERVICEPLEDGEINSTRUCTIONS_LABEL_MAPPING_KEY = "frmRegisterOfPledgesServicePledgeInstructionsLabel";
	
	/** The message resource mapping for the place holder attached to the servicePledgeInstructions property */  
	public static final String SERVICEPLEDGEINSTRUCTIONS_PLACEHOLDER_MAPPING_KEY = "frmRegisterOfPledgesServicePledgeInstructionsPlaceHolder";

	/** The message resource mapping for the help text attached to the servicePledgeInstructions property */  
	public static final String SERVICEPLEDGEINSTRUCTIONS_HELPBLOCK_MAPPING_KEY = "frmRegisterOfPledgesServicePledgeInstructionsHelpBlock";

	/** The message resource mapping for the message that represents the goodsPledgeInstructions property */  
	public static final String GOODSPLEDGEINSTRUCTIONS_MESSAGE_MAPPING_KEY = "frmRegisterOfPledgesGoodsPledgeInstructionsMessage";
  
	/** The message resource mapping for the Label attached to the goodsPledgeInstructions property */  
	public static final String GOODSPLEDGEINSTRUCTIONS_LABEL_MAPPING_KEY = "frmRegisterOfPledgesGoodsPledgeInstructionsLabel";
	
	/** The message resource mapping for the place holder attached to the goodsPledgeInstructions property */  
	public static final String GOODSPLEDGEINSTRUCTIONS_PLACEHOLDER_MAPPING_KEY = "frmRegisterOfPledgesGoodsPledgeInstructionsPlaceHolder";

	/** The message resource mapping for the help text attached to the goodsPledgeInstructions property */  
	public static final String GOODSPLEDGEINSTRUCTIONS_HELPBLOCK_MAPPING_KEY = "frmRegisterOfPledgesGoodsPledgeInstructionsHelpBlock";

    
	/** Entity Id */
	private Long id;

	/** localization messages are bound to a particular view allowing the messages for a distinct view to be loaded*/
	private Long viewId;

	
    /** id of a parent object used when adding objects via JSON enabled restful web services */
    private Long parentObjectId;
    
    
    /** the the newLocale setting which is the locale currently being updated */
    private Long newLocale;

    /** the title as displayed in the browser tab */
    private String formTitle;

    /** the page title as displayed at the top of the page */
    private String viewTitle;
    
    /** the form sub header as displayed below the form header */
	private String formSubHeader;
    
    
    
    private String contactInformationInstructionsMessageKey;
    private String contactInformationInstructionsMessage;
	    
    private String contactInformationInstructionsLabelMessageKey;
    private String contactInformationInstructionsLabel;

    private String contactInformationInstructionsPlaceHolderMessageKey;
    private String contactInformationInstructionsPlaceHolder;
    
    private String contactInformationInstructionsHelpTextMessageKey;
    private String contactInformationInstructionsHelpText;
    
    private String contactInformationInstructionsTooltipMessageKey;
    private String contactInformationInstructionsTooltip;

    private String accommodationPledgeInstructionsMessageKey;
    private String accommodationPledgeInstructionsMessage;
	    
    private String accommodationPledgeInstructionsLabelMessageKey;
    private String accommodationPledgeInstructionsLabel;

    private String accommodationPledgeInstructionsPlaceHolderMessageKey;
    private String accommodationPledgeInstructionsPlaceHolder;
    
    private String accommodationPledgeInstructionsHelpTextMessageKey;
    private String accommodationPledgeInstructionsHelpText;
    
    private String accommodationPledgeInstructionsTooltipMessageKey;
    private String accommodationPledgeInstructionsTooltip;

    private String servicePledgeInstructionsMessageKey;
    private String servicePledgeInstructionsMessage;
	    
    private String servicePledgeInstructionsLabelMessageKey;
    private String servicePledgeInstructionsLabel;

    private String servicePledgeInstructionsPlaceHolderMessageKey;
    private String servicePledgeInstructionsPlaceHolder;
    
    private String servicePledgeInstructionsHelpTextMessageKey;
    private String servicePledgeInstructionsHelpText;
    
    private String servicePledgeInstructionsTooltipMessageKey;
    private String servicePledgeInstructionsTooltip;

    private String goodsPledgeInstructionsMessageKey;
    private String goodsPledgeInstructionsMessage;
	    
    private String goodsPledgeInstructionsLabelMessageKey;
    private String goodsPledgeInstructionsLabel;

    private String goodsPledgeInstructionsPlaceHolderMessageKey;
    private String goodsPledgeInstructionsPlaceHolder;
    
    private String goodsPledgeInstructionsHelpTextMessageKey;
    private String goodsPledgeInstructionsHelpText;
    
    private String goodsPledgeInstructionsTooltipMessageKey;
    private String goodsPledgeInstructionsTooltip;

    
    /**
     * Default Constructor for the RegisterOfPledgesTranslationBackingBean
     */
    public RegisterOfPledgesTranslationBackingBeanImpl()
    {
    	setViewId(RegisterOfPledgesTranslationBackingBeanImpl.VIEW_ID);
		contactInformationInstructionsMessageKey = "";
		contactInformationInstructionsMessage = "";
			contactInformationInstructionsLabelMessageKey = "";
		contactInformationInstructionsLabel = "";
		contactInformationInstructionsPlaceHolderMessageKey = "";
		contactInformationInstructionsPlaceHolder = "";
		contactInformationInstructionsHelpTextMessageKey = "";
		contactInformationInstructionsHelpText = "";
		contactInformationInstructionsTooltipMessageKey = "";
		contactInformationInstructionsTooltip = "";
		accommodationPledgeInstructionsMessageKey = "";
		accommodationPledgeInstructionsMessage = "";
			accommodationPledgeInstructionsLabelMessageKey = "";
		accommodationPledgeInstructionsLabel = "";
		accommodationPledgeInstructionsPlaceHolderMessageKey = "";
		accommodationPledgeInstructionsPlaceHolder = "";
		accommodationPledgeInstructionsHelpTextMessageKey = "";
		accommodationPledgeInstructionsHelpText = "";
		accommodationPledgeInstructionsTooltipMessageKey = "";
		accommodationPledgeInstructionsTooltip = "";
		servicePledgeInstructionsMessageKey = "";
		servicePledgeInstructionsMessage = "";
			servicePledgeInstructionsLabelMessageKey = "";
		servicePledgeInstructionsLabel = "";
		servicePledgeInstructionsPlaceHolderMessageKey = "";
		servicePledgeInstructionsPlaceHolder = "";
		servicePledgeInstructionsHelpTextMessageKey = "";
		servicePledgeInstructionsHelpText = "";
		servicePledgeInstructionsTooltipMessageKey = "";
		servicePledgeInstructionsTooltip = "";
		goodsPledgeInstructionsMessageKey = "";
		goodsPledgeInstructionsMessage = "";
			goodsPledgeInstructionsLabelMessageKey = "";
		goodsPledgeInstructionsLabel = "";
		goodsPledgeInstructionsPlaceHolderMessageKey = "";
		goodsPledgeInstructionsPlaceHolder = "";
		goodsPledgeInstructionsHelpTextMessageKey = "";
		goodsPledgeInstructionsHelpText = "";
		goodsPledgeInstructionsTooltipMessageKey = "";
		goodsPledgeInstructionsTooltip = "";

    }
    
    /*
     * Returns the Id for the underlying database table record
     */
	public Long getId()
	{
        return id;
    }

    /*
     * Sets the Id. This allows front-end forms to bind the id property
     */
	public void setId(Long id)
	{
        this.id = id;
    }
    
    /*
     * Returns the viewId to which the current translations are bound
     */
	public Long getViewId()
	{
        return viewId;
    }

    /*
     * Sets the viewId. This allows the page translations to be bound to a view
     */
	public void setViewId(Long viewId)
	{
        this.viewId = viewId;
    }
    

    /*
     * Returns the parentObjectId when this object has been populated via a restful webservice JSON mapping
     */
	public Long getParentObjectId()
	{
        return parentObjectId;
    }

    /*
     * Sets the parentObjectId. This allows restful web services to bind the parentId property when adding a new record.
     */
	public void setParentObjectId(Long parentObjectId)
	{
        this.parentObjectId = parentObjectId;
    }
    
    /*
     * Returns the newLocale setting which is the locale currently being updated
     */
	public Long getNewLocale()
	{
        return newLocale;
    }

    /*
     * Sets the the newLocale setting which is the locale currently being updated
     */
	public void setNewLocale(Long newLocale)
	{
        this.newLocale = newLocale;
    }

    /*
     * Returns the page title as displayed in the browser tab
     */
	public String getFormTitle()
	{
        return formTitle;
    }

    /*
     * Sets the page title as displayed in the browser tab
     */
	public void setFormTitle(String formTitle)
	{
        this.formTitle = formTitle;
    }
    
    
    /*
     * Returns the page title as displayed at the top of the page
     */
	public String getViewTitle()
	{
        return viewTitle;
    }

    /*
     * Sets the page title as displayed at the top of the page
     */
	public void setViewTitle(String viewTitle)
	{
        this.viewTitle = viewTitle;
    }
    

    /*
     * Returns the form sub header as displayed below the form header
     */
	public String getFormSubHeader()
	{
        return formSubHeader;
    }

    /*
     * Sets the form sub header as displayed below the form header
     */
	public void setFormSubHeader(String formSubHeader)
	{
        this.formSubHeader = formSubHeader;
    }
    

	
    
    /**
     * Sets the contactInformationInstructionsMessageKey
     * @param contactInformationInstructionsMessageKey
     */
    public void setContactInformationInstructionsMessageKey(String contactInformationInstructionsMessageKey)
    {
      this.contactInformationInstructionsMessageKey = contactInformationInstructionsMessageKey;
    }

    /**
     * Returns the contactInformationInstructionsMessageKey
     * @return the contactInformationInstructionsMessageKey
     */
    public String getContactInformationInstructionsMessageKey()
    {
      return contactInformationInstructionsMessageKey;
    }

    /**
     * Sets the contactInformationInstructionsMessage
     * @param contactInformationInstructionsMessage
     */
    public void setContactInformationInstructionsMessage(String contactInformationInstructionsMessage)
    {
      this.contactInformationInstructionsMessage = contactInformationInstructionsMessage;
    }

    /**
     * Returns the contactInformationInstructionsMessage
     * @return the contactInformationInstructionsMessage
     */
    public String getContactInformationInstructionsMessage()
    {
      return contactInformationInstructionsMessage;
    }
    
    
    
    /**
     * Sets the contactInformationInstructionsLabelMessageKey
     * @param contactInformationInstructionsLabelMessageKey
     */
    public void setContactInformationInstructionsLabelMessageKey(String contactInformationInstructionsLabelMessageKey)
    {
      this.contactInformationInstructionsLabelMessageKey = contactInformationInstructionsLabelMessageKey;
    }

    /**
     * Returns the contactInformationInstructionsLabelMessageKey
     * @return the contactInformationInstructionsLabelMessageKey
     */
    public String getContactInformationInstructionsLabelMessageKey()
    {
      return contactInformationInstructionsLabelMessageKey;
    }

    /**
     * Sets the contactInformationInstructionsLabel
     * @param contactInformationInstructionsLabel
     */
    public void setContactInformationInstructionsLabel(String contactInformationInstructionsLabel)
    {
      this.contactInformationInstructionsLabel = contactInformationInstructionsLabel;
    }

    /**
     * Returns the contactInformationInstructionsLabel
     * @return the contactInformationInstructionsLabel
     */
    public String getContactInformationInstructionsLabel()
    {
      return contactInformationInstructionsLabel;
    }
    
    
    /**
     * Sets the contactInformationInstructionsPlaceHolderMessageKey
     * @param contactInformationInstructionsPlaceHolderMessageKey
     */
    public void setContactInformationInstructionsPlaceHolderMessageKey(String contactInformationInstructionsPlaceHolderMessageKey)
    {
      this.contactInformationInstructionsPlaceHolderMessageKey = contactInformationInstructionsPlaceHolderMessageKey;
    }

    /**
     * Returns the contactInformationInstructionsPlaceHolderMessageKey
     * @return the contactInformationInstructionsPlaceHolderMessageKey
     */
    public String getContactInformationInstructionsPlaceHolderMessageKey()
    {
      return contactInformationInstructionsPlaceHolderMessageKey;
    }

    /**
     * Sets the contactInformationInstructionsPlaceHolder
     * @param contactInformationInstructionsPlaceHolder
     */
    public void setContactInformationInstructionsPlaceHolder(String contactInformationInstructionsPlaceHolder)
    {
      this.contactInformationInstructionsPlaceHolder = contactInformationInstructionsPlaceHolder;
    }

    /**
     * Returns the contactInformationInstructionsPlaceHolder
     * @return the contactInformationInstructionsPlaceHolder
     */
    public String getContactInformationInstructionsPlaceHolder()
    {
      return contactInformationInstructionsPlaceHolder;
    }    
    
    /**
     * Sets the contactInformationInstructionsHelpTextMessageKey
     * @param contactInformationInstructionsHelpTextMessageKey
     */
    public void setContactInformationInstructionsHelpTextMessageKey(String contactInformationInstructionsHelpTextMessageKey)
    {
      this.contactInformationInstructionsHelpTextMessageKey = contactInformationInstructionsHelpTextMessageKey;
    }

    /**
     * Returns the contactInformationInstructionsHelpTextMessageKey
     * @return the contactInformationInstructionsHelpTextMessageKey
     */
    public String getContactInformationInstructionsHelpTextMessageKey()
    {
      return contactInformationInstructionsHelpTextMessageKey;
    }

    /**
     * Sets the contactInformationInstructionsHelpText
     * @param contactInformationInstructionsHelpText
     */
    public void setContactInformationInstructionsHelpText(String contactInformationInstructionsHelpText)
    {
      this.contactInformationInstructionsHelpText = contactInformationInstructionsHelpText;
    }

    /**
     * Returns the contactInformationInstructionsHelpText
     * @return the contactInformationInstructionsHelpText
     */
    public String getContactInformationInstructionsHelpText()
    {
      return contactInformationInstructionsHelpText;
    }    
    
    /**
     * Sets the contactInformationInstructionsTooltipMessageKey
     * @param contactInformationInstructionsTooltipMessageKey
     */
    public void setContactInformationInstructionsTooltipMessageKey(String contactInformationInstructionsTooltipMessageKey)
    {
      this.contactInformationInstructionsTooltipMessageKey = contactInformationInstructionsTooltipMessageKey;
    }

    /**
     * Returns the contactInformationInstructionsTooltipMessageKey
     * @return the contactInformationInstructionsTooltipMessageKey
     */
    public String getContactInformationInstructionsTooltipMessageKey()
    {
      return contactInformationInstructionsTooltipMessageKey;
    }

    /**
     * Sets the contactInformationInstructionsTooltip
     * @param contactInformationInstructionsTooltip
     */
    public void setContactInformationInstructionsTooltip(String contactInformationInstructionsTooltip)
    {
      this.contactInformationInstructionsTooltip = contactInformationInstructionsTooltip;
    }

    /**
     * Returns the contactInformationInstructionsTooltip
     * @return the contactInformationInstructionsTooltip
     */
    public String getContactInformationInstructionsTooltip()
    {
      return contactInformationInstructionsTooltip;
    }    

    /**
     * Sets the accommodationPledgeInstructionsMessageKey
     * @param accommodationPledgeInstructionsMessageKey
     */
    public void setAccommodationPledgeInstructionsMessageKey(String accommodationPledgeInstructionsMessageKey)
    {
      this.accommodationPledgeInstructionsMessageKey = accommodationPledgeInstructionsMessageKey;
    }

    /**
     * Returns the accommodationPledgeInstructionsMessageKey
     * @return the accommodationPledgeInstructionsMessageKey
     */
    public String getAccommodationPledgeInstructionsMessageKey()
    {
      return accommodationPledgeInstructionsMessageKey;
    }

    /**
     * Sets the accommodationPledgeInstructionsMessage
     * @param accommodationPledgeInstructionsMessage
     */
    public void setAccommodationPledgeInstructionsMessage(String accommodationPledgeInstructionsMessage)
    {
      this.accommodationPledgeInstructionsMessage = accommodationPledgeInstructionsMessage;
    }

    /**
     * Returns the accommodationPledgeInstructionsMessage
     * @return the accommodationPledgeInstructionsMessage
     */
    public String getAccommodationPledgeInstructionsMessage()
    {
      return accommodationPledgeInstructionsMessage;
    }
    
    
    
    /**
     * Sets the accommodationPledgeInstructionsLabelMessageKey
     * @param accommodationPledgeInstructionsLabelMessageKey
     */
    public void setAccommodationPledgeInstructionsLabelMessageKey(String accommodationPledgeInstructionsLabelMessageKey)
    {
      this.accommodationPledgeInstructionsLabelMessageKey = accommodationPledgeInstructionsLabelMessageKey;
    }

    /**
     * Returns the accommodationPledgeInstructionsLabelMessageKey
     * @return the accommodationPledgeInstructionsLabelMessageKey
     */
    public String getAccommodationPledgeInstructionsLabelMessageKey()
    {
      return accommodationPledgeInstructionsLabelMessageKey;
    }

    /**
     * Sets the accommodationPledgeInstructionsLabel
     * @param accommodationPledgeInstructionsLabel
     */
    public void setAccommodationPledgeInstructionsLabel(String accommodationPledgeInstructionsLabel)
    {
      this.accommodationPledgeInstructionsLabel = accommodationPledgeInstructionsLabel;
    }

    /**
     * Returns the accommodationPledgeInstructionsLabel
     * @return the accommodationPledgeInstructionsLabel
     */
    public String getAccommodationPledgeInstructionsLabel()
    {
      return accommodationPledgeInstructionsLabel;
    }
    
    
    /**
     * Sets the accommodationPledgeInstructionsPlaceHolderMessageKey
     * @param accommodationPledgeInstructionsPlaceHolderMessageKey
     */
    public void setAccommodationPledgeInstructionsPlaceHolderMessageKey(String accommodationPledgeInstructionsPlaceHolderMessageKey)
    {
      this.accommodationPledgeInstructionsPlaceHolderMessageKey = accommodationPledgeInstructionsPlaceHolderMessageKey;
    }

    /**
     * Returns the accommodationPledgeInstructionsPlaceHolderMessageKey
     * @return the accommodationPledgeInstructionsPlaceHolderMessageKey
     */
    public String getAccommodationPledgeInstructionsPlaceHolderMessageKey()
    {
      return accommodationPledgeInstructionsPlaceHolderMessageKey;
    }

    /**
     * Sets the accommodationPledgeInstructionsPlaceHolder
     * @param accommodationPledgeInstructionsPlaceHolder
     */
    public void setAccommodationPledgeInstructionsPlaceHolder(String accommodationPledgeInstructionsPlaceHolder)
    {
      this.accommodationPledgeInstructionsPlaceHolder = accommodationPledgeInstructionsPlaceHolder;
    }

    /**
     * Returns the accommodationPledgeInstructionsPlaceHolder
     * @return the accommodationPledgeInstructionsPlaceHolder
     */
    public String getAccommodationPledgeInstructionsPlaceHolder()
    {
      return accommodationPledgeInstructionsPlaceHolder;
    }    
    
    /**
     * Sets the accommodationPledgeInstructionsHelpTextMessageKey
     * @param accommodationPledgeInstructionsHelpTextMessageKey
     */
    public void setAccommodationPledgeInstructionsHelpTextMessageKey(String accommodationPledgeInstructionsHelpTextMessageKey)
    {
      this.accommodationPledgeInstructionsHelpTextMessageKey = accommodationPledgeInstructionsHelpTextMessageKey;
    }

    /**
     * Returns the accommodationPledgeInstructionsHelpTextMessageKey
     * @return the accommodationPledgeInstructionsHelpTextMessageKey
     */
    public String getAccommodationPledgeInstructionsHelpTextMessageKey()
    {
      return accommodationPledgeInstructionsHelpTextMessageKey;
    }

    /**
     * Sets the accommodationPledgeInstructionsHelpText
     * @param accommodationPledgeInstructionsHelpText
     */
    public void setAccommodationPledgeInstructionsHelpText(String accommodationPledgeInstructionsHelpText)
    {
      this.accommodationPledgeInstructionsHelpText = accommodationPledgeInstructionsHelpText;
    }

    /**
     * Returns the accommodationPledgeInstructionsHelpText
     * @return the accommodationPledgeInstructionsHelpText
     */
    public String getAccommodationPledgeInstructionsHelpText()
    {
      return accommodationPledgeInstructionsHelpText;
    }    
    
    /**
     * Sets the accommodationPledgeInstructionsTooltipMessageKey
     * @param accommodationPledgeInstructionsTooltipMessageKey
     */
    public void setAccommodationPledgeInstructionsTooltipMessageKey(String accommodationPledgeInstructionsTooltipMessageKey)
    {
      this.accommodationPledgeInstructionsTooltipMessageKey = accommodationPledgeInstructionsTooltipMessageKey;
    }

    /**
     * Returns the accommodationPledgeInstructionsTooltipMessageKey
     * @return the accommodationPledgeInstructionsTooltipMessageKey
     */
    public String getAccommodationPledgeInstructionsTooltipMessageKey()
    {
      return accommodationPledgeInstructionsTooltipMessageKey;
    }

    /**
     * Sets the accommodationPledgeInstructionsTooltip
     * @param accommodationPledgeInstructionsTooltip
     */
    public void setAccommodationPledgeInstructionsTooltip(String accommodationPledgeInstructionsTooltip)
    {
      this.accommodationPledgeInstructionsTooltip = accommodationPledgeInstructionsTooltip;
    }

    /**
     * Returns the accommodationPledgeInstructionsTooltip
     * @return the accommodationPledgeInstructionsTooltip
     */
    public String getAccommodationPledgeInstructionsTooltip()
    {
      return accommodationPledgeInstructionsTooltip;
    }    

    /**
     * Sets the servicePledgeInstructionsMessageKey
     * @param servicePledgeInstructionsMessageKey
     */
    public void setServicePledgeInstructionsMessageKey(String servicePledgeInstructionsMessageKey)
    {
      this.servicePledgeInstructionsMessageKey = servicePledgeInstructionsMessageKey;
    }

    /**
     * Returns the servicePledgeInstructionsMessageKey
     * @return the servicePledgeInstructionsMessageKey
     */
    public String getServicePledgeInstructionsMessageKey()
    {
      return servicePledgeInstructionsMessageKey;
    }

    /**
     * Sets the servicePledgeInstructionsMessage
     * @param servicePledgeInstructionsMessage
     */
    public void setServicePledgeInstructionsMessage(String servicePledgeInstructionsMessage)
    {
      this.servicePledgeInstructionsMessage = servicePledgeInstructionsMessage;
    }

    /**
     * Returns the servicePledgeInstructionsMessage
     * @return the servicePledgeInstructionsMessage
     */
    public String getServicePledgeInstructionsMessage()
    {
      return servicePledgeInstructionsMessage;
    }
    
    
    
    /**
     * Sets the servicePledgeInstructionsLabelMessageKey
     * @param servicePledgeInstructionsLabelMessageKey
     */
    public void setServicePledgeInstructionsLabelMessageKey(String servicePledgeInstructionsLabelMessageKey)
    {
      this.servicePledgeInstructionsLabelMessageKey = servicePledgeInstructionsLabelMessageKey;
    }

    /**
     * Returns the servicePledgeInstructionsLabelMessageKey
     * @return the servicePledgeInstructionsLabelMessageKey
     */
    public String getServicePledgeInstructionsLabelMessageKey()
    {
      return servicePledgeInstructionsLabelMessageKey;
    }

    /**
     * Sets the servicePledgeInstructionsLabel
     * @param servicePledgeInstructionsLabel
     */
    public void setServicePledgeInstructionsLabel(String servicePledgeInstructionsLabel)
    {
      this.servicePledgeInstructionsLabel = servicePledgeInstructionsLabel;
    }

    /**
     * Returns the servicePledgeInstructionsLabel
     * @return the servicePledgeInstructionsLabel
     */
    public String getServicePledgeInstructionsLabel()
    {
      return servicePledgeInstructionsLabel;
    }
    
    
    /**
     * Sets the servicePledgeInstructionsPlaceHolderMessageKey
     * @param servicePledgeInstructionsPlaceHolderMessageKey
     */
    public void setServicePledgeInstructionsPlaceHolderMessageKey(String servicePledgeInstructionsPlaceHolderMessageKey)
    {
      this.servicePledgeInstructionsPlaceHolderMessageKey = servicePledgeInstructionsPlaceHolderMessageKey;
    }

    /**
     * Returns the servicePledgeInstructionsPlaceHolderMessageKey
     * @return the servicePledgeInstructionsPlaceHolderMessageKey
     */
    public String getServicePledgeInstructionsPlaceHolderMessageKey()
    {
      return servicePledgeInstructionsPlaceHolderMessageKey;
    }

    /**
     * Sets the servicePledgeInstructionsPlaceHolder
     * @param servicePledgeInstructionsPlaceHolder
     */
    public void setServicePledgeInstructionsPlaceHolder(String servicePledgeInstructionsPlaceHolder)
    {
      this.servicePledgeInstructionsPlaceHolder = servicePledgeInstructionsPlaceHolder;
    }

    /**
     * Returns the servicePledgeInstructionsPlaceHolder
     * @return the servicePledgeInstructionsPlaceHolder
     */
    public String getServicePledgeInstructionsPlaceHolder()
    {
      return servicePledgeInstructionsPlaceHolder;
    }    
    
    /**
     * Sets the servicePledgeInstructionsHelpTextMessageKey
     * @param servicePledgeInstructionsHelpTextMessageKey
     */
    public void setServicePledgeInstructionsHelpTextMessageKey(String servicePledgeInstructionsHelpTextMessageKey)
    {
      this.servicePledgeInstructionsHelpTextMessageKey = servicePledgeInstructionsHelpTextMessageKey;
    }

    /**
     * Returns the servicePledgeInstructionsHelpTextMessageKey
     * @return the servicePledgeInstructionsHelpTextMessageKey
     */
    public String getServicePledgeInstructionsHelpTextMessageKey()
    {
      return servicePledgeInstructionsHelpTextMessageKey;
    }

    /**
     * Sets the servicePledgeInstructionsHelpText
     * @param servicePledgeInstructionsHelpText
     */
    public void setServicePledgeInstructionsHelpText(String servicePledgeInstructionsHelpText)
    {
      this.servicePledgeInstructionsHelpText = servicePledgeInstructionsHelpText;
    }

    /**
     * Returns the servicePledgeInstructionsHelpText
     * @return the servicePledgeInstructionsHelpText
     */
    public String getServicePledgeInstructionsHelpText()
    {
      return servicePledgeInstructionsHelpText;
    }    
    
    /**
     * Sets the servicePledgeInstructionsTooltipMessageKey
     * @param servicePledgeInstructionsTooltipMessageKey
     */
    public void setServicePledgeInstructionsTooltipMessageKey(String servicePledgeInstructionsTooltipMessageKey)
    {
      this.servicePledgeInstructionsTooltipMessageKey = servicePledgeInstructionsTooltipMessageKey;
    }

    /**
     * Returns the servicePledgeInstructionsTooltipMessageKey
     * @return the servicePledgeInstructionsTooltipMessageKey
     */
    public String getServicePledgeInstructionsTooltipMessageKey()
    {
      return servicePledgeInstructionsTooltipMessageKey;
    }

    /**
     * Sets the servicePledgeInstructionsTooltip
     * @param servicePledgeInstructionsTooltip
     */
    public void setServicePledgeInstructionsTooltip(String servicePledgeInstructionsTooltip)
    {
      this.servicePledgeInstructionsTooltip = servicePledgeInstructionsTooltip;
    }

    /**
     * Returns the servicePledgeInstructionsTooltip
     * @return the servicePledgeInstructionsTooltip
     */
    public String getServicePledgeInstructionsTooltip()
    {
      return servicePledgeInstructionsTooltip;
    }    

    /**
     * Sets the goodsPledgeInstructionsMessageKey
     * @param goodsPledgeInstructionsMessageKey
     */
    public void setGoodsPledgeInstructionsMessageKey(String goodsPledgeInstructionsMessageKey)
    {
      this.goodsPledgeInstructionsMessageKey = goodsPledgeInstructionsMessageKey;
    }

    /**
     * Returns the goodsPledgeInstructionsMessageKey
     * @return the goodsPledgeInstructionsMessageKey
     */
    public String getGoodsPledgeInstructionsMessageKey()
    {
      return goodsPledgeInstructionsMessageKey;
    }

    /**
     * Sets the goodsPledgeInstructionsMessage
     * @param goodsPledgeInstructionsMessage
     */
    public void setGoodsPledgeInstructionsMessage(String goodsPledgeInstructionsMessage)
    {
      this.goodsPledgeInstructionsMessage = goodsPledgeInstructionsMessage;
    }

    /**
     * Returns the goodsPledgeInstructionsMessage
     * @return the goodsPledgeInstructionsMessage
     */
    public String getGoodsPledgeInstructionsMessage()
    {
      return goodsPledgeInstructionsMessage;
    }
    
    
    
    /**
     * Sets the goodsPledgeInstructionsLabelMessageKey
     * @param goodsPledgeInstructionsLabelMessageKey
     */
    public void setGoodsPledgeInstructionsLabelMessageKey(String goodsPledgeInstructionsLabelMessageKey)
    {
      this.goodsPledgeInstructionsLabelMessageKey = goodsPledgeInstructionsLabelMessageKey;
    }

    /**
     * Returns the goodsPledgeInstructionsLabelMessageKey
     * @return the goodsPledgeInstructionsLabelMessageKey
     */
    public String getGoodsPledgeInstructionsLabelMessageKey()
    {
      return goodsPledgeInstructionsLabelMessageKey;
    }

    /**
     * Sets the goodsPledgeInstructionsLabel
     * @param goodsPledgeInstructionsLabel
     */
    public void setGoodsPledgeInstructionsLabel(String goodsPledgeInstructionsLabel)
    {
      this.goodsPledgeInstructionsLabel = goodsPledgeInstructionsLabel;
    }

    /**
     * Returns the goodsPledgeInstructionsLabel
     * @return the goodsPledgeInstructionsLabel
     */
    public String getGoodsPledgeInstructionsLabel()
    {
      return goodsPledgeInstructionsLabel;
    }
    
    
    /**
     * Sets the goodsPledgeInstructionsPlaceHolderMessageKey
     * @param goodsPledgeInstructionsPlaceHolderMessageKey
     */
    public void setGoodsPledgeInstructionsPlaceHolderMessageKey(String goodsPledgeInstructionsPlaceHolderMessageKey)
    {
      this.goodsPledgeInstructionsPlaceHolderMessageKey = goodsPledgeInstructionsPlaceHolderMessageKey;
    }

    /**
     * Returns the goodsPledgeInstructionsPlaceHolderMessageKey
     * @return the goodsPledgeInstructionsPlaceHolderMessageKey
     */
    public String getGoodsPledgeInstructionsPlaceHolderMessageKey()
    {
      return goodsPledgeInstructionsPlaceHolderMessageKey;
    }

    /**
     * Sets the goodsPledgeInstructionsPlaceHolder
     * @param goodsPledgeInstructionsPlaceHolder
     */
    public void setGoodsPledgeInstructionsPlaceHolder(String goodsPledgeInstructionsPlaceHolder)
    {
      this.goodsPledgeInstructionsPlaceHolder = goodsPledgeInstructionsPlaceHolder;
    }

    /**
     * Returns the goodsPledgeInstructionsPlaceHolder
     * @return the goodsPledgeInstructionsPlaceHolder
     */
    public String getGoodsPledgeInstructionsPlaceHolder()
    {
      return goodsPledgeInstructionsPlaceHolder;
    }    
    
    /**
     * Sets the goodsPledgeInstructionsHelpTextMessageKey
     * @param goodsPledgeInstructionsHelpTextMessageKey
     */
    public void setGoodsPledgeInstructionsHelpTextMessageKey(String goodsPledgeInstructionsHelpTextMessageKey)
    {
      this.goodsPledgeInstructionsHelpTextMessageKey = goodsPledgeInstructionsHelpTextMessageKey;
    }

    /**
     * Returns the goodsPledgeInstructionsHelpTextMessageKey
     * @return the goodsPledgeInstructionsHelpTextMessageKey
     */
    public String getGoodsPledgeInstructionsHelpTextMessageKey()
    {
      return goodsPledgeInstructionsHelpTextMessageKey;
    }

    /**
     * Sets the goodsPledgeInstructionsHelpText
     * @param goodsPledgeInstructionsHelpText
     */
    public void setGoodsPledgeInstructionsHelpText(String goodsPledgeInstructionsHelpText)
    {
      this.goodsPledgeInstructionsHelpText = goodsPledgeInstructionsHelpText;
    }

    /**
     * Returns the goodsPledgeInstructionsHelpText
     * @return the goodsPledgeInstructionsHelpText
     */
    public String getGoodsPledgeInstructionsHelpText()
    {
      return goodsPledgeInstructionsHelpText;
    }    
    
    /**
     * Sets the goodsPledgeInstructionsTooltipMessageKey
     * @param goodsPledgeInstructionsTooltipMessageKey
     */
    public void setGoodsPledgeInstructionsTooltipMessageKey(String goodsPledgeInstructionsTooltipMessageKey)
    {
      this.goodsPledgeInstructionsTooltipMessageKey = goodsPledgeInstructionsTooltipMessageKey;
    }

    /**
     * Returns the goodsPledgeInstructionsTooltipMessageKey
     * @return the goodsPledgeInstructionsTooltipMessageKey
     */
    public String getGoodsPledgeInstructionsTooltipMessageKey()
    {
      return goodsPledgeInstructionsTooltipMessageKey;
    }

    /**
     * Sets the goodsPledgeInstructionsTooltip
     * @param goodsPledgeInstructionsTooltip
     */
    public void setGoodsPledgeInstructionsTooltip(String goodsPledgeInstructionsTooltip)
    {
      this.goodsPledgeInstructionsTooltip = goodsPledgeInstructionsTooltip;
    }

    /**
     * Returns the goodsPledgeInstructionsTooltip
     * @return the goodsPledgeInstructionsTooltip
     */
    public String getGoodsPledgeInstructionsTooltip()
    {
      return goodsPledgeInstructionsTooltip;
    }    


    /**
     * Checks for a newly created entity object
     * @return true if this is a newly created entity object meaning that it has not yet been persisted, otherwise false
     */
	public boolean isNew() {
		return (this.id == null);
	}
	
    
    
/*     @Override
     public String toString(){
     // TODO: To be implemented
    	return "TODO: to be done";
     }
*/     
}
    
    
    

