package org.volunteertech.pledges.users.service;
import com.netgrains.security.AuthorisationException;
import com.netgrains.security.InvalidUserIDException;
import org.volunteertech.pledges.users.dao.ApplicationUser;
import org.volunteertech.pledges.users.dao.ApplicationUserDetails;
import org.volunteertech.pledges.users.business.ApplicationUserBo;
import org.volunteertech.pledges.users.dao.ApplicationUserFilter;
import org.volunteertech.pledges.users.dao.ApplicationUserHistory;
import org.volunteertech.pledges.users.dao.ApplicationUserLoadException;
import org.volunteertech.pledges.users.dao.ApplicationUserSaveException;
import java.util.List;
import java.util.Set;
import java.util.Date;
import java.math.BigDecimal;
import java.util.Locale;


import com.netgrains.security.EmailExistsException;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UsernameNotFoundException;


import org.volunteertech.pledges.reference.service.ReferenceService;
  
import org.volunteertech.pledges.localisation.service.MessageResourceService;
  


/**
 * The User Model for controlling user access
 * This Interface has been generated by the XSLT processor from the meta data and represents the
 * interface of the Service  Layer Object for the ApplicationUser entity. A Business Object
 * is provided in order to provide a seperation from the Data Access implementation. 
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: * $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">>JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public interface ApplicationUserService
{
    
	/**
	 * Sets the reference Service to perform a user roles lookup
	 */
	public void setReferenceService(ReferenceService referenceService);
	
	/**
	 * Returns a reference to reference Service.
	 */
	public ReferenceService getReferenceService();
	  
	/**
	 * Sets the message resource service to perform localization lookups
	 */
	public void setMessageResourceService(MessageResourceService messageResourceService);
	
	/**
	 * Returns a reference to the message resource service.
	 */
	public MessageResourceService getMessageResourceService();
  
    
    /**
     * Sets the required Business Object (BO)
     * @param applicationUserBo the applicationUserBo used to access the applicationUser entity
     * and it's associations.
     */
    public void setApplicationUserBo(ApplicationUserBo applicationUserBo);
    

    /**
     * Returns the required Business Object (BO)
     * @return the ApplicationUserBo used to access the applicationUser entity
     * and it's associations.
     */
    public ApplicationUserBo getApplicationUserBo();
    

	public boolean autoLoadUser(ApplicationUser applicationUser);

    public ApplicationUser registerNewUserAccount(ApplicationUser applicationUser) throws EmailExistsException, ApplicationUserSaveException;
    

    /**
     * Loads a ApplicationUser object based on the APPLICATIONUSERID column
     * @param APPLICATIONUSERID the primary key for the underlying record.
     * @param userID the userID is checked for authorisation to view the record
     * @ return a ApplicationUser object matching the parameter or null if none can be found. The
     * method also returns null if the parameter is null.
     */
    public ApplicationUser load(Long applicationUserID, Long loggedInUserId) throws ApplicationUserLoadException, AuthorisationException, InvalidUserIDException;
    
    

    /**
     * Load all existing ApplicationUser objects. 
     * @return List a List of ApplicationUser objects.
     */
    public List<ApplicationUser> listApplicationUser();
    
    
    /**
     * Returns a <code>List</code> of ApplicationUser objects that have a matching username
     * @return List a List of ApplicationUser objects that match the username property given as parameter.
     * @param username the username on which to match the required records.
     */
    public List<ApplicationUser> listApplicationUserByUsername(String username);

    /**
     * Returns a <code>List</code> of ApplicationUser objects that have a matching password
     * @return List a List of ApplicationUser objects that match the password property given as parameter.
     * @param password the password on which to match the required records.
     */
    public List<ApplicationUser> listApplicationUserByPassword(String password);

    /**
     * Returns a <code>List</code> of ApplicationUser objects that have a matching enabled
     * @return List a List of ApplicationUser objects that match the enabled property given as parameter.
     * @param enabled the enabled on which to match the required records.
     */
    public List<ApplicationUser> listApplicationUserByEnabled(Boolean enabled);

    /**
     * Returns a <code>List</code> of ApplicationUser objects that have a matching userRoles
     * @return List a List of ApplicationUser objects that match the userRoles property given as parameter.
     * @param userRoles the userRoles on which to match the required records.
     */
    public List<ApplicationUser> listApplicationUserByUserRoles(Long userRoles);

    
    
    /**
     * Load existing ApplicationUser objects from the database that have a createdByID column
     * that matches the userId parameter.
     * @return List a List of ApplicationUser objects that match the userId parameter.
     */
    public List<ApplicationUser> listApplicationUserByCreatedById(Long userId);
    
    
    /**
     * Load all existing ApplicationUserHistory objects for a particular ApplicationUser.
     * The <code>List</code> of ApplicationUserHistory objects contains all of the changes that have been made to the
     * ApplicationUser object identified by the applicationUser parameter'
     * @return List a List of ApplicationUserHistory objects.
     */
    public List<ApplicationUserHistory> listApplicationUserHistory(Long applicationUser) throws Exception;
    
    
    
    /**
     * Either updates an existing entry in the APPLICATIONUSER table or adds a new entry if one does not exist.
     *
     * @param userId the userId of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @throws ApplicationUserLoadException if the existing record cannot be loaded
     * @throws ApplicationUserSaveException if there is an issue populating or saving the updated object
     * @throws AuthorisationException if the user is not authorised to update the object
     * @throws InvalidUserIDException if the userID passed as parameter is not valid
     */
    public void storeApplicationUser(ApplicationUser applicationUser, Long userId)
        throws ApplicationUserSaveException, ApplicationUserLoadException, AuthorisationException, InvalidUserIDException;
    
   
    
    /**
     * Loads a ApplicationUserFilter object based on the participantID of the currently logged in user
     * @param userId the userId is checked for authorisation to view the record. It is also the key to load a against the createdByID
     * column of the underlying record. There should only ever be one or zero filter records per ApplicationUser.
     * @ return a ApplicationUserFilter object matching the parameter or a newly constructed, empty object if none can be found
     */
    public ApplicationUserFilter loadApplicationUserFilter(Long userId) throws ApplicationUserLoadException, AuthorisationException, InvalidUserIDException;


    
    /**
     * Creates a new entry in the APPLICATIONUSERFILTER table containing the parameters passed here.
     *
     * @param userId the userId of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @return the userID which is also the assigned Id for the newly created record.
     * @throws ApplicationUserSaveException on failure to save.  
     */
    public Long createAndStoreApplicationUserFilter(ApplicationUserFilter applicationUserFilter, Long userId)
        throws ApplicationUserSaveException;
    
    
    /**
     * Updates an existing entry in the APPLICATIONUSERFILTER table and associated tables 
     * containing the parameters passed here. If the entry denoted by the userID does not exist then one is created.
     *	
     * @param userId the userId of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @throws ApplicationUserSaveException if there is an issue populating or saving the updated object
     * @throws AuthorisationException if the user is not authorised to update the object
     * @throws InvalidUserIDException if the userID passed as parameter is not valid
     */
    public Long updateApplicationUserFilter(ApplicationUserFilter applicationUserFilter, Long userId)
        throws ApplicationUserLoadException, ApplicationUserSaveException, AuthorisationException, InvalidUserIDException;
    

	/**
	 * Translates the referenceId type properties into the locale specific text for display on the front-end.
	 * @param applicationUser the dto object to be updated with the locale specific translations
	 * @param locale the Locale to be displayed
	 * @return the same ApplicationUser object but with the locale translation fields populated with the message
	 * that is relevant to the current locale
	 */    
    public ApplicationUser translateReferenceValues(ApplicationUser applicationUser, Locale locale);
    
	/**
	 * Translates the referenceId type properties into the locale specific text for display on the front-end.
	 * @param applicationUserList the dto object to be updated with the locale specific translations
	 * @param locale the Locale to be displayed
	 */    
    public List<ApplicationUser> translateReferenceValues(List<ApplicationUser> applicationUserList, Locale locale);
    
    
    /**
     * @param details
     * @return
     */
//    public ApplicationUser getApplicationUserByDetails(ApplicationUserDetails details);
    
	
    
}    
