package org.volunteertech.pledges.users.dao;
import java.util.Date;
import java.math.BigDecimal;

/**
 * The contact information
 * This class has been generated by the XSLT processor from the metadata and represents the
 * DataBase access handler for the ApplicationUserDetails entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public class ApplicationUserDetailsHistory
{
	/** Hibernate Id */
	private Long id;
	
	/** id from the parent table for which this represents an historic record **/
	private Long applicationUserDetailsID;
	 
    
    /** the contact Name of the pledger */
    private String contactName;
	
    /** the pledge is from an organisation */
    private Long representOrganisation;
	
    /** An example of a Telephone Number */
    private String telephoneNumber;
	
    /** the street or house address */
    private String addressOne;
	
    /** the town or city address */
    private String addressTwo;
	
    /** the post code */
    private String city;
	
    /** the post code */
    private String stateProvinceRegion;
	
    /** the post code */
    private String postCode;
	
    /** the address type */
    private Long country;
	
    /** the contact email address where the contact type is email. */
    private String emailAddress;
	     
    
    /** The user ID of the person that originally created the underlying record **/
    private Long createdByID;

    /** The user ID of the person that last updated the underlying record **/
    private Long updatedByID;

    /** The date that the underlying record was created DD/MM/YYYY-HH:MM format **/
    private Date dateCreated;

    /** The date that the underlying record was last updated DD/MM/YYYY-HH:MM format **/
    private Date dateUpdated;
    

    /**
     * Default Constructor for the ApplicationUserDetails bean
     */
    public ApplicationUserDetailsHistory()
    {
    	applicationUserDetailsID = Long.valueOf(0);
    	contactName = "";
		representOrganisation = Long.valueOf("0");
		telephoneNumber = "";
		addressOne = "";
		addressTwo = "";
		city = "";
		stateProvinceRegion = "";
		postCode = "";
		country = Long.valueOf("0");
		emailAddress = "";
		
    }
    
    /*
     * Returns the Id for the underlying database table record
     */
	public Long getId()
	{
        return id;
    }

	/**
	 * We usually do not manipulate the identity of an object, hence the setter method should be private.
	 */
	@SuppressWarnings("unused")
    private void setId(Long id)
    {
        this.id = id;
    }    


    /*
     * Returns the ApplicationUserDetailsID for the parent record
     */
	public Long getApplicationUserDetailsID()
	{
        return applicationUserDetailsID;
    }

	/**
	 * We usually do not manipulate the identity of an object, hence the setter method should be private.
	 */
	@SuppressWarnings("unused")
    private void setApplicationUserDetailsID(Long applicationUserDetailsID)
    {
        this.applicationUserDetailsID = applicationUserDetailsID;
    }    

    

    
    
    /**
     * Sets the contact Name of the pledger
     * @param contactName is the contact Name of the pledger
     */
    public void setContactName(String contactName)
    {
      this.contactName = contactName;
    }

    /**
     * Returns the contact Name of the pledger
     * @return the contact Name of the pledger
     */
    public String getContactName()
    {
      return contactName;
    }

    
    /**
     * Sets the pledge is from an organisation that has been chosen by the user
     * @param representOrganisation is the pledge is from an organisation
     */
    public void setRepresentOrganisation(Long representOrganisation)
    {
      this.representOrganisation = representOrganisation;
    }

    /**
     * Returns the pledge is from an organisation that has been chosen by the user or saved in the database
     * @return the pledge is from an organisation
     */
    public Long getRepresentOrganisation()
    {
      return representOrganisation;
    }

    
    /**
     * Sets An example of a Telephone Number
     * @param telephoneNumber is An example of a Telephone Number
     */
    public void setTelephoneNumber(String telephoneNumber)
    {
      this.telephoneNumber = telephoneNumber;
    }

    /**
     * Returns An example of a Telephone Number
     * @return An example of a Telephone Number
     */
    public String getTelephoneNumber()
    {
      return telephoneNumber;
    }

    
    /**
     * Sets the street or house address
     * @param addressOne is the street or house address
     */
    public void setAddressOne(String addressOne)
    {
      this.addressOne = addressOne;
    }

    /**
     * Returns the street or house address
     * @return the street or house address
     */
    public String getAddressOne()
    {
      return addressOne;
    }

    
    /**
     * Sets the town or city address
     * @param addressTwo is the town or city address
     */
    public void setAddressTwo(String addressTwo)
    {
      this.addressTwo = addressTwo;
    }

    /**
     * Returns the town or city address
     * @return the town or city address
     */
    public String getAddressTwo()
    {
      return addressTwo;
    }

    
    /**
     * Sets the post code
     * @param city is the post code
     */
    public void setCity(String city)
    {
      this.city = city;
    }

    /**
     * Returns the post code
     * @return the post code
     */
    public String getCity()
    {
      return city;
    }

    
    /**
     * Sets the post code
     * @param stateProvinceRegion is the post code
     */
    public void setStateProvinceRegion(String stateProvinceRegion)
    {
      this.stateProvinceRegion = stateProvinceRegion;
    }

    /**
     * Returns the post code
     * @return the post code
     */
    public String getStateProvinceRegion()
    {
      return stateProvinceRegion;
    }

    
    /**
     * Sets the post code
     * @param postCode is the post code
     */
    public void setPostCode(String postCode)
    {
      this.postCode = postCode;
    }

    /**
     * Returns the post code
     * @return the post code
     */
    public String getPostCode()
    {
      return postCode;
    }

    
    /**
     * Sets the address type that has been chosen by the user
     * @param country is the address type
     */
    public void setCountry(Long country)
    {
      this.country = country;
    }

    /**
     * Returns the address type that has been chosen by the user or saved in the database
     * @return the address type
     */
    public Long getCountry()
    {
      return country;
    }

    
    /**
     * Sets the contact email address where the contact type is email.
     * @param emailAddress is the contact email address where the contact type is email.
     */
    public void setEmailAddress(String emailAddress)
    {
      this.emailAddress = emailAddress;
    }

    /**
     * Returns the contact email address where the contact type is email.
     * @return the contact email address where the contact type is email.
     */
    public String getEmailAddress()
    {
      return emailAddress;
    }


    /**
     * sets the ID of the user that created the underlying record
     */
    public void setCreatedByID(Long createdByID)
    {
        this.createdByID = createdByID;
    }


    /**
     * gets the ID of the user that created the underlying record
     */
    public Long getCreatedByID()
    {
        return createdByID;
    }
     
     
    /**
     * sets the ID of the user that last updated the underlying record
     */
    public void setUpdatedByID(Long updatedByID)
    {
        this.updatedByID = updatedByID;
    }
     
     
    /**
     * gets the ID of the user that last updated the underlying record
     */
    public Long getUpdatedByID()
    {
        return updatedByID;
    }


    /**
     * sets the date that the underlying record was first created as a <code>java.util.Date</code> object
     */
    public void setDateCreated(Date dateCreated)
    {
        this.dateCreated = dateCreated;
    }

     
    /**
     * Gets the date that the underlying record was first created as a <code>java.util.Date</code> object
     */
    public Date getDateCreated()
    {
        return dateCreated;
    }

    /**
     * sets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     */
    public void setDateUpdated(Date dateUpdated)
    {
        this.dateUpdated = dateUpdated;
    }


    
    /**
     * Gets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     */
    public Date getDateUpdated()
    {
        return dateUpdated;
    }
    
     
}
    
    
    

