package org.volunteertech.pledges.users.business;
import com.netgrains.security.AuthorisationException;
import com.netgrains.security.InvalidUserIDException;
import org.volunteertech.pledges.users.dao.ApplicationUser;
import org.volunteertech.pledges.users.dao.ApplicationUserDao;
import org.volunteertech.pledges.users.dao.ApplicationUserFilter;
import org.volunteertech.pledges.users.dao.ApplicationUserHistory;
import org.volunteertech.pledges.users.dao.ApplicationUserLoadException;
import org.volunteertech.pledges.users.dao.ApplicationUserSaveException;
import java.util.List;
import java.util.Set;
import java.util.Date;
import java.math.BigDecimal;



/**
 * The User Model for controlling user access
 * This Interface has been generated by the XSLT processor from the meta data and represents the
 * interface of the Business Object(BO) for the ApplicationUser entity. A Business Object
 * is provided in order to provide a seperation from the Data Access implementation. 
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: * $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">>JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public interface ApplicationUserBo
{
    
    
    /**
     * Sets the required Data Access Object (DAO)
     * @param applicationUserDao the applicationUserDao used to access the applicationUser entity.
     */
    public void setApplicationUserDao(ApplicationUserDao applicationUserDao);
    

    /**
     * Returns the required Data Access Object (DAO)
     * @return the ApplicationUserDao used to access the applicationUser entity.
     */
    public ApplicationUserDao getApplicationUserDao();
    

    
    /**
     * Loads a ApplicationUser object based on the APPLICATIONUSERID column
     * @param APPLICATIONUSERID the primary key for the underlying record.
     * @param userID the userID is checked for authorisation to view the record
     * @ return a ApplicationUser object matching the parameter or null if none can be found. The
     * method also returns null if the parameter is null.
     */
    public ApplicationUser load(Long applicationUserID, Long loggedInUserId) throws ApplicationUserLoadException, AuthorisationException, InvalidUserIDException;
    
    

    /**
     * Load all existing ApplicationUser objects. 
     * @return List a List of ApplicationUser objects.
     */
    public List<ApplicationUser> listApplicationUser();
    
    
    /**
     * Returns a <code>List</code> of ApplicationUser objects that have a matching username
     * @return List a List of ApplicationUser objects that match the username property given as parameter.
     * @param username the username on which to match the required records.
     */
    public List<ApplicationUser> listApplicationUserByUsername(String username);

    /**
     * Returns a <code>List</code> of ApplicationUser objects that have a matching password
     * @return List a List of ApplicationUser objects that match the password property given as parameter.
     * @param password the password on which to match the required records.
     */
    public List<ApplicationUser> listApplicationUserByPassword(String password);

    /**
     * Returns a <code>List</code> of ApplicationUser objects that have a matching enabled
     * @return List a List of ApplicationUser objects that match the enabled property given as parameter.
     * @param enabled the enabled on which to match the required records.
     */
    public List<ApplicationUser> listApplicationUserByEnabled(Boolean enabled);

    /**
     * Returns a <code>List</code> of ApplicationUser objects that have a matching userRoles
     * @return List a List of ApplicationUser objects that match the userRoles property given as parameter.
     * @param userRoles the userRoles on which to match the required records.
     */
    public List<ApplicationUser> listApplicationUserByUserRoles(Long userRoles);

    
    /**
     * Load existing ApplicationUser objects from the database that have a createdByID column
     * that matches the userId parameter.
     * @return List a List of ApplicationUser objects that match the userId parameter.
     */
    public List<ApplicationUser> listApplicationUserByCreatedById(Long userId);
    
    
    /**
     * Load all existing ApplicationUserHistory objects for a particular ApplicationUser.
     * The <code>List</code> of ApplicationUserHistory objects contains all of the changes that have been made to the
     * ApplicationUser object identified by the applicationUser parameter'
     * @return List a List of ApplicationUserHistory objects.
     */
    public List<ApplicationUserHistory> listApplicationUserHistory(Long applicationUser) throws Exception;
    
        
    
    /**
     * Creates a new entry in the APPLICATIONUSER table containing the parameters passed here.
     *
     * @param userID the userID of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @return the database generated Id of the newly created record.
     * @throws ApplicationUserSaveException on failure to save.  
     */
    public Long createAndStoreApplicationUser(ApplicationUser applicationUser, Long userID)
        throws ApplicationUserSaveException;


    /**
     * Updates an existing entry in the APPLICATIONUSER table containing the parameters passed here.
     * Only non-null parameters will be applied to the underlying table so preserving any existing entries.
     *
     * @param userID the userID of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @throws ApplicationUserLoadException if the existing record cannot be loaded
     * @throws ApplicationUserSaveException if there is an issue populating or saving the updated object
     * @throws AuthorisationException if the user is not authorised to update the object
     * @throws InvalidUserIDException if the userID passed as parameter is not valid
     */
    public void updateApplicationUser(ApplicationUser applicationUser, Long userID)
        throws ApplicationUserSaveException, ApplicationUserLoadException, AuthorisationException, InvalidUserIDException;
    
    
    /**
     * Loads a ApplicationUserFilter object based on the participantID of the currently logged in user
     * @param userId the userId is checked for authorisation to view the record. It is also the key to load a against the createdByID
     * column of the underlying record. There should only ever be one or zero filter records per ApplicationUser.
     * @ return a ApplicationUserFilter object matching the parameter or a newly constructed, empty object if none can be found
     */
    public ApplicationUserFilter loadApplicationUserFilter(Long userId) throws ApplicationUserLoadException, AuthorisationException, InvalidUserIDException;


    
    /**
     * Creates a new entry in the APPLICATIONUSERFILTER table containing the parameters passed here.
     *
     * @param userId the userId of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @return the userId which is also the assigned Id for the newly created record.
     * @throws ApplicationUserSaveException on failure to save.  
     */
    public Long createAndStoreApplicationUserFilter(ApplicationUserFilter applicationUserFilter, Long userId)
        throws ApplicationUserSaveException;
    
    
    /**
     * Updates an existing entry in the APPLICATIONUSERFILTER table and associated tables 
     * containing the parameters passed here. If the entry denoted by the userID does not exist then one is created.
     *	
     * @param userId the userId of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @throws ApplicationUserSaveException if there is an issue populating or saving the updated object
     * @throws AuthorisationException if the user is not authorised to update the object
     * @throws InvalidUserIDException if the userID passed as parameter is not valid
     */
    public Long updateApplicationUserFilter(ApplicationUserFilter applicationUserFilter, Long userId)
        throws ApplicationUserLoadException, ApplicationUserSaveException, AuthorisationException, InvalidUserIDException;
    
}
    
