package org.volunteertech.pledges.startup.web;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.SortedMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.Locale;

import org.volunteertech.pledges.startup.dao.Landing;
import org.volunteertech.pledges.startup.dao.LandingImpl;
import org.volunteertech.pledges.startup.service.LandingService;
import org.volunteertech.pledges.startup.dao.LandingLoadException;
import org.volunteertech.pledges.startup.dao.LandingSaveException;
import org.volunteertech.pledges.startup.validator.LandingFormValidator;
import org.volunteertech.pledges.main.web.BaseController;
import org.volunteertech.pledges.users.security.SecurityUser;

import org.volunteertech.pledges.reference.ReferenceStore;





/**
 * The main web screen
 * The Spring LandingRestController to handle restful web service requests.
 * This class has been generated by the XSLT processor from the metadata and represents the
 * the Spring LandingRestController to handle restful web service requests.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">>JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
@RestController
public class LandingRestController extends BaseController
{
	final Logger logger = LoggerFactory.getLogger(LandingRestController.class);
	
	@Autowired
	private ReferenceStore referenceStore;
	
	@Autowired
	private LandingService landingService;
	
	


	/**
	 * Returns a JSON representation of all Landing records
	 * @return the JSON representation of all Landing.
	 */
	@RequestMapping(value = "/restful/landing/list", method = RequestMethod.GET)
	@ResponseBody
    public List<Landing> showAllLanding(Authentication authentication, Locale locale) {
		logger.info("Inside restful getLanding method...");
		List <Landing> landingList = null;
		SecurityUser user = (SecurityUser)authentication.getPrincipal();
        Long userId = user.getApplicationUser().getId();		
		
		try{
			// TODO: Needs exception handling policy
	    	landingList = landingService.listLanding();
	    	landingList = landingService.translateReferenceValues(landingList, locale);
		}
		catch (Exception ex){
			logger.error("Exception caught !!!!!!!!!!!!!!", ex);
		}		
		
		
    	return landingList;
    }


	
	/**
	 * Returns a JSON representation of the Landing record that matches the id parameter
	 * @param id the primary key by which to search
	 * @return the Landing with the relevant primary key.
	 */
	@RequestMapping(value = "/restful/landing", method = RequestMethod.GET)
	@ResponseBody
    public Landing getLanding(Authentication authentication, @RequestParam(value="id") String id) {
		logger.info("Inside restful getLanding method...");
		Landing landing = null;
		SecurityUser user = (SecurityUser)authentication.getPrincipal();
        Long userId = user.getApplicationUser().getId();		
		
		try{
			// TODO: Needs exception handling policy
	    	landing = landingService.load(Long.valueOf(id), userId);
		}
		catch (Exception ex){
			logger.error("Exception caught !!!!!!!!!!!!!!", ex);
		}		
		
		
    	return landing;
    }
    
    @RequestMapping(value = "/restful/landing/update", method = RequestMethod.POST)
    @ResponseBody
    public List<Landing> updateLanding(Authentication authentication, @RequestBody Landing landing) {
        logger.debug("In the updateLanding controller and got Id: " + landing.getId());

		SecurityUser user = (SecurityUser)authentication.getPrincipal();
        Long userId = user.getApplicationUser().getId();
        
		try{
			// TODO needs security update
			landingService.storeLanding(landing, userId);
		}
		catch (Exception ex){
		// TODO needs custom exception handling
		logger.error("Exception caught !!!!!!!!!!!!!!", ex);
		}
    	List<Landing> landingList = landingService.listLanding();
        
        return landingList;
    }
    
    
    @RequestMapping(value = "/restful/landing/new", method = RequestMethod.POST)
    @ResponseBody
    public List<Landing> addLanding(Authentication authentication, @RequestBody Landing landing) {
        logger.debug("In the addLanding controller and got Id: " + landing.getId());
        SecurityUser user = (SecurityUser)authentication.getPrincipal();
        Long userId = user.getApplicationUser().getId();

		try{
			// TODO needs security update
			landingService.storeLanding(landing, userId);
		}
		catch (Exception ex){
		// TODO needs custom exception handling
		logger.error("Exception caught !!!!!!!!!!!!!!", ex);
		}
    	List<Landing> landingList = landingService.listLanding();
        
        return landingList;
    }
    
    
    
}
