package org.volunteertech.pledges.startup.view;

import org.volunteertech.pledges.startup.dao.Landing;
import java.io.Serializable;





/**
 * The main web screen
 * The LandingTranslationBacking Bean supports the localisation of the Landing Screen
 * This class has been generated by the XSLT processor from the metadata and represents the
 * DataBase access handler for the Landing entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public interface LandingTranslationBackingBean extends Landing{ 

    
    /*
     * Returns the Id for the underlying database table record
     */
	public Long getId();
	
    
    /*
     * Sets the Id. This allows front-end forms to bind the id property
     */
	public void setId(Long id);
	
	
    /*
     * Returns the parentObjectId when this object has been populated via a restful webservice JSON mapping
     */
	public Long getParentObjectId();
	

    /*
     * Sets the parentObjectId. This allows restful web services to bind the parentId property when adding a new record.
     */
	public void setParentObjectId(Long parentObjectId);
	

    

    /**
     * Checks for a newly created entity object
     * @return true if this is a newly created entity object meaning that it has not yet been persisted, otherwise false
     */
	public boolean isNew();
	
    
    
     @Override
     public String toString();
     
}
    
    
    

