package org.volunteertech.pledges.goodspledge.dao;
    
/**
 * The goods pledge screen is used to add/edit a new/existing pledge of services
 * This class has been generated by the XSLT processor from the metadata and represents the
 * LoadException for the GoodsPledge entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: * $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">>JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
@SuppressWarnings("serial") 
public class GoodsPledgeLoadException extends Exception
{
    /**
     * Create a GoodsPledgeLoadException Object to give details
     * of issues loading from the database.
     * @param pledgedGoods A supporting message
     * @param cause The Exception that caused the original error.
     */
    public GoodsPledgeLoadException(String message, Throwable cause)
    {
        super(message, cause);
    }
    
    
    /**
     * Create a GoodsPledgeLoadException Object to give details
     * of issues loading from the database.
     * @param pledgedGoods A supporting message
     */
    public GoodsPledgeLoadException(String message)
    {
        super(message);
    }
    
}
