package org.volunteertech.pledges.goodspledge.dao;
import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import java.util.HashSet;
import java.math.BigDecimal;


import org.volunteertech.pledges.pledge.dao.RegisterOfPledges;




/**
 * The goods pledge screen is used to add/edit a new/existing pledge of services
 * This Interface has been generated by the XSLT processor from the metadata and represents the
 * DataBase access handler interface for the GoodsPledge entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public interface GoodsPledge extends Serializable { 

    public enum CurrentMode{
    	ADD,UPDATE,LOCALIZE;
    	
    	public String toString(){
    		switch(this){
    			case ADD: return "ADD";
    			case UPDATE: return "UPDATE";
    			case LOCALIZE: return "LOCALIZE";
    			default: return "UNKNOWN";
    		}	
    	}
    }
    	
    /**
     * Returns the Id for the underlying database table record
     * @return the Id for the underlying database table record
     */
	public Long getId();
	
    /**
     * Sets the Id. This allows front-end forms to bind the id property.
     * @param id the Id for the underlying database table record.
     */
	public void setId(Long id);
	
    /**
     * Returns the parentObjectId when this object has been populated via a restful webservice JSON mapping
     * @return the parentObjectId when this object has been populated via a restful webservice JSON mapping
     */
	public Long getParentObjectId();
	
    /**
     * Sets the parentObjectId. This allows restful web services to bind the parentId property when adding a new record.
     * @param parentObjectId allows restful web services to bind the parentId property when adding a new record.
     */
	public void setParentObjectId(Long parentObjectId);
    
    
    /**
     * Sets the goods category level one that has been chosen by the user
     * @param goodsCategoryOne is the goods category level one
     */
    public void setGoodsCategoryOne(Long goodsCategoryOne);

    /**
     * Returns the goods category level one that has been chosen by the user or saved in the database
     * @return the goods category level one
     */
    public Long getGoodsCategoryOne();
    
    /**
     * Sets the translated reference mapping for the goods category level one that has been chosen by the user
     * @param the translated reference mapping for goodsCategoryOne is the goods category level one
     */
    public void setGoodsCategoryOneReferenceTranslation(String goodsCategoryOneReferenceTranslation);

    /**
     * Returns the translated reference mapping for the goods category level one that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the goods category level one
     */
    public String getGoodsCategoryOneReferenceTranslation();
      
    
    /**
     * Sets the goods category level two that has been chosen by the user
     * @param goodsCategoryTwo is the goods category level two
     */
    public void setGoodsCategoryTwo(Long goodsCategoryTwo);

    /**
     * Returns the goods category level two that has been chosen by the user or saved in the database
     * @return the goods category level two
     */
    public Long getGoodsCategoryTwo();
    
    /**
     * Sets the translated reference mapping for the goods category level two that has been chosen by the user
     * @param the translated reference mapping for goodsCategoryTwo is the goods category level two
     */
    public void setGoodsCategoryTwoReferenceTranslation(String goodsCategoryTwoReferenceTranslation);

    /**
     * Returns the translated reference mapping for the goods category level two that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the goods category level two
     */
    public String getGoodsCategoryTwoReferenceTranslation();
      
    
    /**
     * Sets the goods category level three that has been chosen by the user
     * @param goodsCategoryThree is the goods category level three
     */
    public void setGoodsCategoryThree(Long goodsCategoryThree);

    /**
     * Returns the goods category level three that has been chosen by the user or saved in the database
     * @return the goods category level three
     */
    public Long getGoodsCategoryThree();
    
    /**
     * Sets the translated reference mapping for the goods category level three that has been chosen by the user
     * @param the translated reference mapping for goodsCategoryThree is the goods category level three
     */
    public void setGoodsCategoryThreeReferenceTranslation(String goodsCategoryThreeReferenceTranslation);

    /**
     * Returns the translated reference mapping for the goods category level three that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the goods category level three
     */
    public String getGoodsCategoryThreeReferenceTranslation();
      
    
    /**
     * Sets the goods size that has been chosen by the user
     * @param goodsSize is the goods size
     */
    public void setGoodsSize(Long goodsSize);

    /**
     * Returns the goods size that has been chosen by the user or saved in the database
     * @return the goods size
     */
    public Long getGoodsSize();
    
    /**
     * Sets the translated reference mapping for the goods size that has been chosen by the user
     * @param the translated reference mapping for goodsSize is the goods size
     */
    public void setGoodsSizeReferenceTranslation(String goodsSizeReferenceTranslation);

    /**
     * Returns the translated reference mapping for the goods size that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the goods size
     */
    public String getGoodsSizeReferenceTranslation();
      
    
    /**
     * Sets the goods size that has been chosen by the user
     * @param goodsNewOrUsed is the goods size
     */
    public void setGoodsNewOrUsed(Long goodsNewOrUsed);

    /**
     * Returns the goods size that has been chosen by the user or saved in the database
     * @return the goods size
     */
    public Long getGoodsNewOrUsed();
    
    /**
     * Sets the translated reference mapping for the goods size that has been chosen by the user
     * @param the translated reference mapping for goodsNewOrUsed is the goods size
     */
    public void setGoodsNewOrUsedReferenceTranslation(String goodsNewOrUsedReferenceTranslation);

    /**
     * Returns the translated reference mapping for the goods size that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the goods size
     */
    public String getGoodsNewOrUsedReferenceTranslation();
      
    
    /**
     * Sets the goods condition that has been chosen by the user
     * @param goodsCondition is the goods condition
     */
    public void setGoodsCondition(Long goodsCondition);

    /**
     * Returns the goods condition that has been chosen by the user or saved in the database
     * @return the goods condition
     */
    public Long getGoodsCondition();
    
    /**
     * Sets the translated reference mapping for the goods condition that has been chosen by the user
     * @param the translated reference mapping for goodsCondition is the goods condition
     */
    public void setGoodsConditionReferenceTranslation(String goodsConditionReferenceTranslation);

    /**
     * Returns the translated reference mapping for the goods condition that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the goods condition
     */
    public String getGoodsConditionReferenceTranslation();
      
    
    /**
     * Sets the quantity of goods that has been chosen by the user
     * @param goodsQuantity is the quantity of goods
     */
    public void setGoodsQuantity(Long goodsQuantity);

    /**
     * Returns the quantity of goods that has been chosen by the user or saved in the database
     * @return the quantity of goods
     */
    public Long getGoodsQuantity();
    
    /**
     * Sets the translated reference mapping for the quantity of goods that has been chosen by the user
     * @param the translated reference mapping for goodsQuantity is the quantity of goods
     */
    public void setGoodsQuantityReferenceTranslation(String goodsQuantityReferenceTranslation);

    /**
     * Returns the translated reference mapping for the quantity of goods that has been chosen by the user or saved in the database
     * @return the translated reference mapping for the quantity of goods
     */
    public String getGoodsQuantityReferenceTranslation();
      
    
    /**
     * Sets the participant comments
     * @param additionalInformation is the participant comments
     */
    public void setAdditionalInformation(String additionalInformation);

    /**
     * Returns the participant comments
     * @return the participant comments
     */
    public String getAdditionalInformation();
    
    
    /**
     * Sets the participant comments
     * @param itemSize is the participant comments
     */
    public void setItemSize(String itemSize);

    /**
     * Returns the participant comments
     * @return the participant comments
     */
    public String getItemSize();
    
    /**
     * Sets the associated RegisterOfPledges mapped as the registerOfPledges property
     * @param the associated RegisterOfPledges mapped as the registerOfPledges property
     */
    public void setRegisterOfPledges(RegisterOfPledges registerOfPledges);

    /**
     * Returns the associated RegisterOfPledges mapped as the registerOfPledges property
     * @return the associated RegisterOfPledges mapped as the registerOfPledges property
     */
    public RegisterOfPledges getRegisterOfPledges();
  

    /**
     * sets the Id of the user that created the underlying record
     * @param createdByID the Id of the user that created the underlying record
     */
    public void setCreatedByID(Long createdByID);
    
    /**
     * gets the Id of the user that created the underlying record
     * @return the Id of the user that created the underlying record
     */
    public Long getCreatedByID();
         
   	/**
     * sets the Id of the user that last updated the underlying record
     * @param updatedByID the Id of the user that last updated the underlying record
     */
    public void setUpdatedByID(Long updatedByID);
     
    /**
     * gets the Id of the user that last updated the underlying record
     * @return the Id of the user that last updated the underlying record
     */
    public Long getUpdatedByID();

    /**
     * sets the date that the underlying record was first created as a <code>java.util.Date</code> object
     * @param dateCreated the date that the underlying record was first created
     */
    public void setDateCreated(Date dateCreated);

    /**
     * Gets the date that the underlying record was first created as a <code>java.util.Date</code> object
     * @return the date that the underlying record was first created
     */
    public Date getDateCreated();

    /**
     * Sets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     * @param dateUpdated the date that the underlying record was last updated
     */
    public void setDateUpdated(Date dateUpdated);
    
    /**
     * Gets the date that the underlying record was last updated as a <code>java.util.Date</code> object
     * @return the date that the underlying record was last updated
     */
    public Date getDateUpdated();
    
    /**
     * Checks for a newly created entity object
     * @return true if this is a newly created entity object meaning that it has not yet been persisted, otherwise false
     */
	public boolean isNew();
	
	/**
	 * Sets the current mode of use for the entity object;
	 * @param mode a member of the CurrentMode enumeration
	 */
	public void setCurrentMode(CurrentMode mode);

    /**
     * Returns the current mode under which the class instance was loaded
     * @return A member of the CurrentMode Enumeration
     */
	public CurrentMode getCurrentMode();
	
	
	public Date getDateAvailableFrom();
	
	public void setDateAvailableFrom(Date d);
	
	public Date getDateAvailableTo();
	
	public void setDateAvailableTo(Date d);
}
    
    
    

