package org.volunteertech.pledges.goodspledge.view;

import org.volunteertech.pledges.goodspledge.dao.GoodsPledge;
import java.io.Serializable;


import org.volunteertech.pledges.pledge.dao.RegisterOfPledges;

import org.volunteertech.pledges.pledge.dao.RegisterOfPledges;




/**
 * The goods pledge screen is used to add/edit a new/existing pledge of services
 * The GoodsPledgeTranslationBacking Bean supports the localisation of the GoodsPledge Screen
 * This class has been generated by the XSLT processor from the metadata and represents the
 * DataBase access handler for the GoodsPledge entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public interface GoodsPledgeTranslationBackingBean extends GoodsPledge{ 

    
    /*
     * Returns the Id for the underlying database table record
     */
	public Long getId();
	
    
    /*
     * Sets the Id. This allows front-end forms to bind the id property
     */
	public void setId(Long id);
	
	
    /*
     * Returns the parentObjectId when this object has been populated via a restful webservice JSON mapping
     */
	public Long getParentObjectId();
	

    /*
     * Sets the parentObjectId. This allows restful web services to bind the parentId property when adding a new record.
     */
	public void setParentObjectId(Long parentObjectId);
	

    
    
    /**
     * Sets the goodsCategoryOneLabelMessageKey
     * @param goodsCategoryOneLabelMessageKey
     */
    public void setGoodsCategoryOneLabelMessageKey(String goodsCategoryOneLabelMessageKey);
    
    
    /**
     * Returns the goodsCategoryOneLabelMessageKey
     * @return the goodsCategoryOneLabelMessageKey
     */
    public String getGoodsCategoryOneLabelMessageKey();
    
    
    /**
     * Sets the goodsCategoryOneLabel
     * @param goodsCategoryOneLabel
     */
    public void setGoodsCategoryOneLabel(String goodsCategoryOneLabel);
    
    
    /**
     * Returns the goodsCategoryOneLabel
     * @return the goodsCategoryOneLabel
     */
    public String getGoodsCategoryOneLabel();
    
    
    /**
     * Sets the goodsCategoryOnePlaceHolderMessageKey
     * @param goodsCategoryOnePlaceHolderMessageKey
     */
    public void setGoodsCategoryOnePlaceHolderMessageKey(String goodsCategoryOnePlaceHolderMessageKey);
    
    
    /**
     * Returns the goodsCategoryOnePlaceHolderMessageKey
     * @return the goodsCategoryOnePlaceHolderMessageKey
     */
    public String getGoodsCategoryOnePlaceHolderMessageKey();
    
    
    /**
     * Sets the goodsCategoryOnePlaceHolder
     * @param goodsCategoryOnePlaceHolder
     */
    public void setGoodsCategoryOnePlaceHolder(String goodsCategoryOnePlaceHolder);
    
    
    /**
     * Returns the goodsCategoryOnePlaceHolder
     * @return the goodsCategoryOnePlaceHolder
     */
    public String getGoodsCategoryOnePlaceHolder();
    
    
    /**
     * Sets the goodsCategoryOneHelpTextMessageKey
     * @param goodsCategoryOneHelpTextMessageKey
     */
    public void setGoodsCategoryOneHelpTextMessageKey(String goodsCategoryOneHelpTextMessageKey);
    
    
    /**
     * Returns the goodsCategoryOneHelpTextMessageKey
     * @return the goodsCategoryOneHelpTextMessageKey
     */
    public String getGoodsCategoryOneHelpTextMessageKey();
    
    
    /**
     * Sets the goodsCategoryOneHelpText
     * @param goodsCategoryOneHelpText
     */
    public void setGoodsCategoryOneHelpText(String goodsCategoryOneHelpText);
    
    
    /**
     * Returns the goodsCategoryOneHelpText
     * @return the goodsCategoryOneHelpText
     */
    public String getGoodsCategoryOneHelpText();
    
    
    /**
     * Sets the goodsCategoryOneTooltipMessageKey
     * @param goodsCategoryOneTooltipMessageKey
     */
    public void setGoodsCategoryOneTooltipMessageKey(String goodsCategoryOneTooltipMessageKey);
    
    
    /**
     * Returns the goodsCategoryOneTooltipMessageKey
     * @return the goodsCategoryOneTooltipMessageKey
     */
    public String getGoodsCategoryOneTooltipMessageKey();
    
    
    /**
     * Sets the goodsCategoryOneTooltip
     * @param goodsCategoryOneTooltip
     */
    public void setGoodsCategoryOneTooltip(String goodsCategoryOneTooltip);
    
    
    /**
     * Returns the goodsCategoryOneTooltip
     * @return the goodsCategoryOneTooltip
     */
    public String getGoodsCategoryOneTooltip();
    
        

    
    /**
     * Sets the goodsCategoryTwoLabelMessageKey
     * @param goodsCategoryTwoLabelMessageKey
     */
    public void setGoodsCategoryTwoLabelMessageKey(String goodsCategoryTwoLabelMessageKey);
    
    
    /**
     * Returns the goodsCategoryTwoLabelMessageKey
     * @return the goodsCategoryTwoLabelMessageKey
     */
    public String getGoodsCategoryTwoLabelMessageKey();
    
    
    /**
     * Sets the goodsCategoryTwoLabel
     * @param goodsCategoryTwoLabel
     */
    public void setGoodsCategoryTwoLabel(String goodsCategoryTwoLabel);
    
    
    /**
     * Returns the goodsCategoryTwoLabel
     * @return the goodsCategoryTwoLabel
     */
    public String getGoodsCategoryTwoLabel();
    
    
    /**
     * Sets the goodsCategoryTwoPlaceHolderMessageKey
     * @param goodsCategoryTwoPlaceHolderMessageKey
     */
    public void setGoodsCategoryTwoPlaceHolderMessageKey(String goodsCategoryTwoPlaceHolderMessageKey);
    
    
    /**
     * Returns the goodsCategoryTwoPlaceHolderMessageKey
     * @return the goodsCategoryTwoPlaceHolderMessageKey
     */
    public String getGoodsCategoryTwoPlaceHolderMessageKey();
    
    
    /**
     * Sets the goodsCategoryTwoPlaceHolder
     * @param goodsCategoryTwoPlaceHolder
     */
    public void setGoodsCategoryTwoPlaceHolder(String goodsCategoryTwoPlaceHolder);
    
    
    /**
     * Returns the goodsCategoryTwoPlaceHolder
     * @return the goodsCategoryTwoPlaceHolder
     */
    public String getGoodsCategoryTwoPlaceHolder();
    
    
    /**
     * Sets the goodsCategoryTwoHelpTextMessageKey
     * @param goodsCategoryTwoHelpTextMessageKey
     */
    public void setGoodsCategoryTwoHelpTextMessageKey(String goodsCategoryTwoHelpTextMessageKey);
    
    
    /**
     * Returns the goodsCategoryTwoHelpTextMessageKey
     * @return the goodsCategoryTwoHelpTextMessageKey
     */
    public String getGoodsCategoryTwoHelpTextMessageKey();
    
    
    /**
     * Sets the goodsCategoryTwoHelpText
     * @param goodsCategoryTwoHelpText
     */
    public void setGoodsCategoryTwoHelpText(String goodsCategoryTwoHelpText);
    
    
    /**
     * Returns the goodsCategoryTwoHelpText
     * @return the goodsCategoryTwoHelpText
     */
    public String getGoodsCategoryTwoHelpText();
    
    
    /**
     * Sets the goodsCategoryTwoTooltipMessageKey
     * @param goodsCategoryTwoTooltipMessageKey
     */
    public void setGoodsCategoryTwoTooltipMessageKey(String goodsCategoryTwoTooltipMessageKey);
    
    
    /**
     * Returns the goodsCategoryTwoTooltipMessageKey
     * @return the goodsCategoryTwoTooltipMessageKey
     */
    public String getGoodsCategoryTwoTooltipMessageKey();
    
    
    /**
     * Sets the goodsCategoryTwoTooltip
     * @param goodsCategoryTwoTooltip
     */
    public void setGoodsCategoryTwoTooltip(String goodsCategoryTwoTooltip);
    
    
    /**
     * Returns the goodsCategoryTwoTooltip
     * @return the goodsCategoryTwoTooltip
     */
    public String getGoodsCategoryTwoTooltip();
    
        

    
    /**
     * Sets the goodsCategoryThreeLabelMessageKey
     * @param goodsCategoryThreeLabelMessageKey
     */
    public void setGoodsCategoryThreeLabelMessageKey(String goodsCategoryThreeLabelMessageKey);
    
    
    /**
     * Returns the goodsCategoryThreeLabelMessageKey
     * @return the goodsCategoryThreeLabelMessageKey
     */
    public String getGoodsCategoryThreeLabelMessageKey();
    
    
    /**
     * Sets the goodsCategoryThreeLabel
     * @param goodsCategoryThreeLabel
     */
    public void setGoodsCategoryThreeLabel(String goodsCategoryThreeLabel);
    
    
    /**
     * Returns the goodsCategoryThreeLabel
     * @return the goodsCategoryThreeLabel
     */
    public String getGoodsCategoryThreeLabel();
    
    
    /**
     * Sets the goodsCategoryThreePlaceHolderMessageKey
     * @param goodsCategoryThreePlaceHolderMessageKey
     */
    public void setGoodsCategoryThreePlaceHolderMessageKey(String goodsCategoryThreePlaceHolderMessageKey);
    
    
    /**
     * Returns the goodsCategoryThreePlaceHolderMessageKey
     * @return the goodsCategoryThreePlaceHolderMessageKey
     */
    public String getGoodsCategoryThreePlaceHolderMessageKey();
    
    
    /**
     * Sets the goodsCategoryThreePlaceHolder
     * @param goodsCategoryThreePlaceHolder
     */
    public void setGoodsCategoryThreePlaceHolder(String goodsCategoryThreePlaceHolder);
    
    
    /**
     * Returns the goodsCategoryThreePlaceHolder
     * @return the goodsCategoryThreePlaceHolder
     */
    public String getGoodsCategoryThreePlaceHolder();
    
    
    /**
     * Sets the goodsCategoryThreeHelpTextMessageKey
     * @param goodsCategoryThreeHelpTextMessageKey
     */
    public void setGoodsCategoryThreeHelpTextMessageKey(String goodsCategoryThreeHelpTextMessageKey);
    
    
    /**
     * Returns the goodsCategoryThreeHelpTextMessageKey
     * @return the goodsCategoryThreeHelpTextMessageKey
     */
    public String getGoodsCategoryThreeHelpTextMessageKey();
    
    
    /**
     * Sets the goodsCategoryThreeHelpText
     * @param goodsCategoryThreeHelpText
     */
    public void setGoodsCategoryThreeHelpText(String goodsCategoryThreeHelpText);
    
    
    /**
     * Returns the goodsCategoryThreeHelpText
     * @return the goodsCategoryThreeHelpText
     */
    public String getGoodsCategoryThreeHelpText();
    
    
    /**
     * Sets the goodsCategoryThreeTooltipMessageKey
     * @param goodsCategoryThreeTooltipMessageKey
     */
    public void setGoodsCategoryThreeTooltipMessageKey(String goodsCategoryThreeTooltipMessageKey);
    
    
    /**
     * Returns the goodsCategoryThreeTooltipMessageKey
     * @return the goodsCategoryThreeTooltipMessageKey
     */
    public String getGoodsCategoryThreeTooltipMessageKey();
    
    
    /**
     * Sets the goodsCategoryThreeTooltip
     * @param goodsCategoryThreeTooltip
     */
    public void setGoodsCategoryThreeTooltip(String goodsCategoryThreeTooltip);
    
    
    /**
     * Returns the goodsCategoryThreeTooltip
     * @return the goodsCategoryThreeTooltip
     */
    public String getGoodsCategoryThreeTooltip();
    
        

    
    /**
     * Sets the goodsSizeLabelMessageKey
     * @param goodsSizeLabelMessageKey
     */
    public void setGoodsSizeLabelMessageKey(String goodsSizeLabelMessageKey);
    
    
    /**
     * Returns the goodsSizeLabelMessageKey
     * @return the goodsSizeLabelMessageKey
     */
    public String getGoodsSizeLabelMessageKey();
    
    
    /**
     * Sets the goodsSizeLabel
     * @param goodsSizeLabel
     */
    public void setGoodsSizeLabel(String goodsSizeLabel);
    
    
    /**
     * Returns the goodsSizeLabel
     * @return the goodsSizeLabel
     */
    public String getGoodsSizeLabel();
    
    
    /**
     * Sets the goodsSizePlaceHolderMessageKey
     * @param goodsSizePlaceHolderMessageKey
     */
    public void setGoodsSizePlaceHolderMessageKey(String goodsSizePlaceHolderMessageKey);
    
    
    /**
     * Returns the goodsSizePlaceHolderMessageKey
     * @return the goodsSizePlaceHolderMessageKey
     */
    public String getGoodsSizePlaceHolderMessageKey();
    
    
    /**
     * Sets the goodsSizePlaceHolder
     * @param goodsSizePlaceHolder
     */
    public void setGoodsSizePlaceHolder(String goodsSizePlaceHolder);
    
    
    /**
     * Returns the goodsSizePlaceHolder
     * @return the goodsSizePlaceHolder
     */
    public String getGoodsSizePlaceHolder();
    
    
    /**
     * Sets the goodsSizeHelpTextMessageKey
     * @param goodsSizeHelpTextMessageKey
     */
    public void setGoodsSizeHelpTextMessageKey(String goodsSizeHelpTextMessageKey);
    
    
    /**
     * Returns the goodsSizeHelpTextMessageKey
     * @return the goodsSizeHelpTextMessageKey
     */
    public String getGoodsSizeHelpTextMessageKey();
    
    
    /**
     * Sets the goodsSizeHelpText
     * @param goodsSizeHelpText
     */
    public void setGoodsSizeHelpText(String goodsSizeHelpText);
    
    
    /**
     * Returns the goodsSizeHelpText
     * @return the goodsSizeHelpText
     */
    public String getGoodsSizeHelpText();
    
    
    /**
     * Sets the goodsSizeTooltipMessageKey
     * @param goodsSizeTooltipMessageKey
     */
    public void setGoodsSizeTooltipMessageKey(String goodsSizeTooltipMessageKey);
    
    
    /**
     * Returns the goodsSizeTooltipMessageKey
     * @return the goodsSizeTooltipMessageKey
     */
    public String getGoodsSizeTooltipMessageKey();
    
    
    /**
     * Sets the goodsSizeTooltip
     * @param goodsSizeTooltip
     */
    public void setGoodsSizeTooltip(String goodsSizeTooltip);
    
    
    /**
     * Returns the goodsSizeTooltip
     * @return the goodsSizeTooltip
     */
    public String getGoodsSizeTooltip();
    
        

    
    /**
     * Sets the goodsNewOrUsedLabelMessageKey
     * @param goodsNewOrUsedLabelMessageKey
     */
    public void setGoodsNewOrUsedLabelMessageKey(String goodsNewOrUsedLabelMessageKey);
    
    
    /**
     * Returns the goodsNewOrUsedLabelMessageKey
     * @return the goodsNewOrUsedLabelMessageKey
     */
    public String getGoodsNewOrUsedLabelMessageKey();
    
    
    /**
     * Sets the goodsNewOrUsedLabel
     * @param goodsNewOrUsedLabel
     */
    public void setGoodsNewOrUsedLabel(String goodsNewOrUsedLabel);
    
    
    /**
     * Returns the goodsNewOrUsedLabel
     * @return the goodsNewOrUsedLabel
     */
    public String getGoodsNewOrUsedLabel();
    
    
    /**
     * Sets the goodsNewOrUsedPlaceHolderMessageKey
     * @param goodsNewOrUsedPlaceHolderMessageKey
     */
    public void setGoodsNewOrUsedPlaceHolderMessageKey(String goodsNewOrUsedPlaceHolderMessageKey);
    
    
    /**
     * Returns the goodsNewOrUsedPlaceHolderMessageKey
     * @return the goodsNewOrUsedPlaceHolderMessageKey
     */
    public String getGoodsNewOrUsedPlaceHolderMessageKey();
    
    
    /**
     * Sets the goodsNewOrUsedPlaceHolder
     * @param goodsNewOrUsedPlaceHolder
     */
    public void setGoodsNewOrUsedPlaceHolder(String goodsNewOrUsedPlaceHolder);
    
    
    /**
     * Returns the goodsNewOrUsedPlaceHolder
     * @return the goodsNewOrUsedPlaceHolder
     */
    public String getGoodsNewOrUsedPlaceHolder();
    
    
    /**
     * Sets the goodsNewOrUsedHelpTextMessageKey
     * @param goodsNewOrUsedHelpTextMessageKey
     */
    public void setGoodsNewOrUsedHelpTextMessageKey(String goodsNewOrUsedHelpTextMessageKey);
    
    
    /**
     * Returns the goodsNewOrUsedHelpTextMessageKey
     * @return the goodsNewOrUsedHelpTextMessageKey
     */
    public String getGoodsNewOrUsedHelpTextMessageKey();
    
    
    /**
     * Sets the goodsNewOrUsedHelpText
     * @param goodsNewOrUsedHelpText
     */
    public void setGoodsNewOrUsedHelpText(String goodsNewOrUsedHelpText);
    
    
    /**
     * Returns the goodsNewOrUsedHelpText
     * @return the goodsNewOrUsedHelpText
     */
    public String getGoodsNewOrUsedHelpText();
    
    
    /**
     * Sets the goodsNewOrUsedTooltipMessageKey
     * @param goodsNewOrUsedTooltipMessageKey
     */
    public void setGoodsNewOrUsedTooltipMessageKey(String goodsNewOrUsedTooltipMessageKey);
    
    
    /**
     * Returns the goodsNewOrUsedTooltipMessageKey
     * @return the goodsNewOrUsedTooltipMessageKey
     */
    public String getGoodsNewOrUsedTooltipMessageKey();
    
    
    /**
     * Sets the goodsNewOrUsedTooltip
     * @param goodsNewOrUsedTooltip
     */
    public void setGoodsNewOrUsedTooltip(String goodsNewOrUsedTooltip);
    
    
    /**
     * Returns the goodsNewOrUsedTooltip
     * @return the goodsNewOrUsedTooltip
     */
    public String getGoodsNewOrUsedTooltip();
    
        

    
    /**
     * Sets the goodsConditionLabelMessageKey
     * @param goodsConditionLabelMessageKey
     */
    public void setGoodsConditionLabelMessageKey(String goodsConditionLabelMessageKey);
    
    
    /**
     * Returns the goodsConditionLabelMessageKey
     * @return the goodsConditionLabelMessageKey
     */
    public String getGoodsConditionLabelMessageKey();
    
    
    /**
     * Sets the goodsConditionLabel
     * @param goodsConditionLabel
     */
    public void setGoodsConditionLabel(String goodsConditionLabel);
    
    
    /**
     * Returns the goodsConditionLabel
     * @return the goodsConditionLabel
     */
    public String getGoodsConditionLabel();
    
    
    /**
     * Sets the goodsConditionPlaceHolderMessageKey
     * @param goodsConditionPlaceHolderMessageKey
     */
    public void setGoodsConditionPlaceHolderMessageKey(String goodsConditionPlaceHolderMessageKey);
    
    
    /**
     * Returns the goodsConditionPlaceHolderMessageKey
     * @return the goodsConditionPlaceHolderMessageKey
     */
    public String getGoodsConditionPlaceHolderMessageKey();
    
    
    /**
     * Sets the goodsConditionPlaceHolder
     * @param goodsConditionPlaceHolder
     */
    public void setGoodsConditionPlaceHolder(String goodsConditionPlaceHolder);
    
    
    /**
     * Returns the goodsConditionPlaceHolder
     * @return the goodsConditionPlaceHolder
     */
    public String getGoodsConditionPlaceHolder();
    
    
    /**
     * Sets the goodsConditionHelpTextMessageKey
     * @param goodsConditionHelpTextMessageKey
     */
    public void setGoodsConditionHelpTextMessageKey(String goodsConditionHelpTextMessageKey);
    
    
    /**
     * Returns the goodsConditionHelpTextMessageKey
     * @return the goodsConditionHelpTextMessageKey
     */
    public String getGoodsConditionHelpTextMessageKey();
    
    
    /**
     * Sets the goodsConditionHelpText
     * @param goodsConditionHelpText
     */
    public void setGoodsConditionHelpText(String goodsConditionHelpText);
    
    
    /**
     * Returns the goodsConditionHelpText
     * @return the goodsConditionHelpText
     */
    public String getGoodsConditionHelpText();
    
    
    /**
     * Sets the goodsConditionTooltipMessageKey
     * @param goodsConditionTooltipMessageKey
     */
    public void setGoodsConditionTooltipMessageKey(String goodsConditionTooltipMessageKey);
    
    
    /**
     * Returns the goodsConditionTooltipMessageKey
     * @return the goodsConditionTooltipMessageKey
     */
    public String getGoodsConditionTooltipMessageKey();
    
    
    /**
     * Sets the goodsConditionTooltip
     * @param goodsConditionTooltip
     */
    public void setGoodsConditionTooltip(String goodsConditionTooltip);
    
    
    /**
     * Returns the goodsConditionTooltip
     * @return the goodsConditionTooltip
     */
    public String getGoodsConditionTooltip();
    
        

    
    /**
     * Sets the goodsQuantityLabelMessageKey
     * @param goodsQuantityLabelMessageKey
     */
    public void setGoodsQuantityLabelMessageKey(String goodsQuantityLabelMessageKey);
    
    
    /**
     * Returns the goodsQuantityLabelMessageKey
     * @return the goodsQuantityLabelMessageKey
     */
    public String getGoodsQuantityLabelMessageKey();
    
    
    /**
     * Sets the goodsQuantityLabel
     * @param goodsQuantityLabel
     */
    public void setGoodsQuantityLabel(String goodsQuantityLabel);
    
    
    /**
     * Returns the goodsQuantityLabel
     * @return the goodsQuantityLabel
     */
    public String getGoodsQuantityLabel();
    
    
    /**
     * Sets the goodsQuantityPlaceHolderMessageKey
     * @param goodsQuantityPlaceHolderMessageKey
     */
    public void setGoodsQuantityPlaceHolderMessageKey(String goodsQuantityPlaceHolderMessageKey);
    
    
    /**
     * Returns the goodsQuantityPlaceHolderMessageKey
     * @return the goodsQuantityPlaceHolderMessageKey
     */
    public String getGoodsQuantityPlaceHolderMessageKey();
    
    
    /**
     * Sets the goodsQuantityPlaceHolder
     * @param goodsQuantityPlaceHolder
     */
    public void setGoodsQuantityPlaceHolder(String goodsQuantityPlaceHolder);
    
    
    /**
     * Returns the goodsQuantityPlaceHolder
     * @return the goodsQuantityPlaceHolder
     */
    public String getGoodsQuantityPlaceHolder();
    
    
    /**
     * Sets the goodsQuantityHelpTextMessageKey
     * @param goodsQuantityHelpTextMessageKey
     */
    public void setGoodsQuantityHelpTextMessageKey(String goodsQuantityHelpTextMessageKey);
    
    
    /**
     * Returns the goodsQuantityHelpTextMessageKey
     * @return the goodsQuantityHelpTextMessageKey
     */
    public String getGoodsQuantityHelpTextMessageKey();
    
    
    /**
     * Sets the goodsQuantityHelpText
     * @param goodsQuantityHelpText
     */
    public void setGoodsQuantityHelpText(String goodsQuantityHelpText);
    
    
    /**
     * Returns the goodsQuantityHelpText
     * @return the goodsQuantityHelpText
     */
    public String getGoodsQuantityHelpText();
    
    
    /**
     * Sets the goodsQuantityTooltipMessageKey
     * @param goodsQuantityTooltipMessageKey
     */
    public void setGoodsQuantityTooltipMessageKey(String goodsQuantityTooltipMessageKey);
    
    
    /**
     * Returns the goodsQuantityTooltipMessageKey
     * @return the goodsQuantityTooltipMessageKey
     */
    public String getGoodsQuantityTooltipMessageKey();
    
    
    /**
     * Sets the goodsQuantityTooltip
     * @param goodsQuantityTooltip
     */
    public void setGoodsQuantityTooltip(String goodsQuantityTooltip);
    
    
    /**
     * Returns the goodsQuantityTooltip
     * @return the goodsQuantityTooltip
     */
    public String getGoodsQuantityTooltip();
    
        

    
    /**
     * Sets the additionalInformationLabelMessageKey
     * @param additionalInformationLabelMessageKey
     */
    public void setAdditionalInformationLabelMessageKey(String additionalInformationLabelMessageKey);
    
    
    /**
     * Returns the additionalInformationLabelMessageKey
     * @return the additionalInformationLabelMessageKey
     */
    public String getAdditionalInformationLabelMessageKey();
    
    
    /**
     * Sets the additionalInformationLabel
     * @param additionalInformationLabel
     */
    public void setAdditionalInformationLabel(String additionalInformationLabel);
    
    
    /**
     * Returns the additionalInformationLabel
     * @return the additionalInformationLabel
     */
    public String getAdditionalInformationLabel();
    
    
    /**
     * Sets the additionalInformationPlaceHolderMessageKey
     * @param additionalInformationPlaceHolderMessageKey
     */
    public void setAdditionalInformationPlaceHolderMessageKey(String additionalInformationPlaceHolderMessageKey);
    
    
    /**
     * Returns the additionalInformationPlaceHolderMessageKey
     * @return the additionalInformationPlaceHolderMessageKey
     */
    public String getAdditionalInformationPlaceHolderMessageKey();
    
    
    /**
     * Sets the additionalInformationPlaceHolder
     * @param additionalInformationPlaceHolder
     */
    public void setAdditionalInformationPlaceHolder(String additionalInformationPlaceHolder);
    
    
    /**
     * Returns the additionalInformationPlaceHolder
     * @return the additionalInformationPlaceHolder
     */
    public String getAdditionalInformationPlaceHolder();
    
    
    /**
     * Sets the additionalInformationHelpTextMessageKey
     * @param additionalInformationHelpTextMessageKey
     */
    public void setAdditionalInformationHelpTextMessageKey(String additionalInformationHelpTextMessageKey);
    
    
    /**
     * Returns the additionalInformationHelpTextMessageKey
     * @return the additionalInformationHelpTextMessageKey
     */
    public String getAdditionalInformationHelpTextMessageKey();
    
    
    /**
     * Sets the additionalInformationHelpText
     * @param additionalInformationHelpText
     */
    public void setAdditionalInformationHelpText(String additionalInformationHelpText);
    
    
    /**
     * Returns the additionalInformationHelpText
     * @return the additionalInformationHelpText
     */
    public String getAdditionalInformationHelpText();
    
    
    /**
     * Sets the additionalInformationTooltipMessageKey
     * @param additionalInformationTooltipMessageKey
     */
    public void setAdditionalInformationTooltipMessageKey(String additionalInformationTooltipMessageKey);
    
    
    /**
     * Returns the additionalInformationTooltipMessageKey
     * @return the additionalInformationTooltipMessageKey
     */
    public String getAdditionalInformationTooltipMessageKey();
    
    
    /**
     * Sets the additionalInformationTooltip
     * @param additionalInformationTooltip
     */
    public void setAdditionalInformationTooltip(String additionalInformationTooltip);
    
    
    /**
     * Returns the additionalInformationTooltip
     * @return the additionalInformationTooltip
     */
    public String getAdditionalInformationTooltip();
    
        

    
    /**
     * Sets the itemSizeLabelMessageKey
     * @param itemSizeLabelMessageKey
     */
    public void setItemSizeLabelMessageKey(String itemSizeLabelMessageKey);
    
    
    /**
     * Returns the itemSizeLabelMessageKey
     * @return the itemSizeLabelMessageKey
     */
    public String getItemSizeLabelMessageKey();
    
    
    /**
     * Sets the itemSizeLabel
     * @param itemSizeLabel
     */
    public void setItemSizeLabel(String itemSizeLabel);
    
    
    /**
     * Returns the itemSizeLabel
     * @return the itemSizeLabel
     */
    public String getItemSizeLabel();
    
    
    /**
     * Sets the itemSizePlaceHolderMessageKey
     * @param itemSizePlaceHolderMessageKey
     */
    public void setItemSizePlaceHolderMessageKey(String itemSizePlaceHolderMessageKey);
    
    
    /**
     * Returns the itemSizePlaceHolderMessageKey
     * @return the itemSizePlaceHolderMessageKey
     */
    public String getItemSizePlaceHolderMessageKey();
    
    
    /**
     * Sets the itemSizePlaceHolder
     * @param itemSizePlaceHolder
     */
    public void setItemSizePlaceHolder(String itemSizePlaceHolder);
    
    
    /**
     * Returns the itemSizePlaceHolder
     * @return the itemSizePlaceHolder
     */
    public String getItemSizePlaceHolder();
    
    
    /**
     * Sets the itemSizeHelpTextMessageKey
     * @param itemSizeHelpTextMessageKey
     */
    public void setItemSizeHelpTextMessageKey(String itemSizeHelpTextMessageKey);
    
    
    /**
     * Returns the itemSizeHelpTextMessageKey
     * @return the itemSizeHelpTextMessageKey
     */
    public String getItemSizeHelpTextMessageKey();
    
    
    /**
     * Sets the itemSizeHelpText
     * @param itemSizeHelpText
     */
    public void setItemSizeHelpText(String itemSizeHelpText);
    
    
    /**
     * Returns the itemSizeHelpText
     * @return the itemSizeHelpText
     */
    public String getItemSizeHelpText();
    
    
    /**
     * Sets the itemSizeTooltipMessageKey
     * @param itemSizeTooltipMessageKey
     */
    public void setItemSizeTooltipMessageKey(String itemSizeTooltipMessageKey);
    
    
    /**
     * Returns the itemSizeTooltipMessageKey
     * @return the itemSizeTooltipMessageKey
     */
    public String getItemSizeTooltipMessageKey();
    
    
    /**
     * Sets the itemSizeTooltip
     * @param itemSizeTooltip
     */
    public void setItemSizeTooltip(String itemSizeTooltip);
    
    
    /**
     * Returns the itemSizeTooltip
     * @return the itemSizeTooltip
     */
    public String getItemSizeTooltip();
    
        


    /**
     * Checks for a newly created entity object
     * @return true if this is a newly created entity object meaning that it has not yet been persisted, otherwise false
     */
	public boolean isNew();
	
    
    
     @Override
     public String toString();
     
}
    
    
    

