package org.volunteertech.pledges.goodspledge.view;

import org.volunteertech.pledges.goodspledge.dao.GoodsPledgeImpl;
import java.io.Serializable;


import org.volunteertech.pledges.pledge.dao.RegisterOfPledges;




/**
 * The goods pledge screen is used to add/edit a new/existing pledge of services
 * The GoodsPledgeTranslationBacking Bean supports the localisation of the GoodsPledge Screen
 * This class has been generated by the XSLT processor from the metadata and represents the
 * DataBase access handler for the GoodsPledge entity.
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public class GoodsPledgeTranslationBackingBeanImpl extends GoodsPledgeImpl implements GoodsPledgeTranslationBackingBean, Serializable { 

    private static final long serialVersionUID = 1L;
    
    /** The identifier for the Goods Pledge view */
    public static final Long VIEW_ID = new Long(5);
    
    /** The mapping key for the page title as displayed in the browser tab */
    public static String GOODSPLEDGE_TITLE_MAPPING_KEY = "goodspledge.form.title";
    
    /** The mapping key for the page header text as displayed at the top of the page */
    public static String GOODSPLEDGE_HEADER_MAPPING_KEY = "goodspledge.form.header";
    
    /** The mapping key for the form sub header */
    public static String GOODSPLEDGE_SUBHEADER_MAPPING_KEY = "goodspledge.form.subheader";
    
    
	/** The message resource mapping for the Label attached to the pledgedGoods property */  
	public static final String PLEDGEDGOODS_LABEL_MAPPING_KEY = "frmGoodsPledgePledgedGoodsLabel";
	
	/** The message resource mapping for the place holder attached to the pledgedGoods property */  
	public static final String PLEDGEDGOODS_PLACEHOLDER_MAPPING_KEY = "frmGoodsPledgePledgedGoodsPlaceHolder";

	/** The message resource mapping for the help text attached to the pledgedGoods property */  
	public static final String PLEDGEDGOODS_HELPBLOCK_MAPPING_KEY = "frmGoodsPledgePledgedGoodsHelpBlock";

	/** The message resource mapping for the Label attached to the additionalInformation property */  
	public static final String ADDITIONALINFORMATION_LABEL_MAPPING_KEY = "frmGoodsPledgeAdditionalInformationLabel";
	
	/** The message resource mapping for the place holder attached to the additionalInformation property */  
	public static final String ADDITIONALINFORMATION_PLACEHOLDER_MAPPING_KEY = "frmGoodsPledgeAdditionalInformationPlaceHolder";

	/** The message resource mapping for the help text attached to the additionalInformation property */  
	public static final String ADDITIONALINFORMATION_HELPBLOCK_MAPPING_KEY = "frmGoodsPledgeAdditionalInformationHelpBlock";

	/** The message resource mapping for the Label attached to the itemSize property */  
	public static final String ITEMSIZE_LABEL_MAPPING_KEY = "frmGoodsPledgeItemSizeLabel";
	
	/** The message resource mapping for the place holder attached to the itemSize property */  
	public static final String ITEMSIZE_PLACEHOLDER_MAPPING_KEY = "frmGoodsPledgeItemSizePlaceHolder";

	/** The message resource mapping for the help text attached to the itemSize property */  
	public static final String ITEMSIZE_HELPBLOCK_MAPPING_KEY = "frmGoodsPledgeItemSizeHelpBlock";

	/** The message resource mapping for the Label attached to the goodsCondition property */  
	public static final String GOODSCONDITION_LABEL_MAPPING_KEY = "frmGoodsPledgeGoodsConditionLabel";
	
	/** The message resource mapping for the place holder attached to the goodsCondition property */  
	public static final String GOODSCONDITION_PLACEHOLDER_MAPPING_KEY = "frmGoodsPledgeGoodsConditionPlaceHolder";

	/** The message resource mapping for the help text attached to the goodsCondition property */  
	public static final String GOODSCONDITION_HELPBLOCK_MAPPING_KEY = "frmGoodsPledgeGoodsConditionHelpBlock";

	/** The message resource mapping for the Label attached to the numberOfItems property */  
	public static final String NUMBEROFITEMS_LABEL_MAPPING_KEY = "frmGoodsPledgeNumberOfItemsLabel";
	
	/** The message resource mapping for the place holder attached to the numberOfItems property */  
	public static final String NUMBEROFITEMS_PLACEHOLDER_MAPPING_KEY = "frmGoodsPledgeNumberOfItemsPlaceHolder";

	/** The message resource mapping for the help text attached to the numberOfItems property */  
	public static final String NUMBEROFITEMS_HELPBLOCK_MAPPING_KEY = "frmGoodsPledgeNumberOfItemsHelpBlock";

	/** The message resource mapping for the Label attached to the saveButton property */  
	public static final String SAVEBUTTON_LABEL_MAPPING_KEY = "frmGoodsPledgeSaveButtonLabel";
	
	/** The message resource mapping for the place holder attached to the saveButton property */  
	public static final String SAVEBUTTON_PLACEHOLDER_MAPPING_KEY = "frmGoodsPledgeSaveButtonPlaceHolder";

	/** The message resource mapping for the help text attached to the saveButton property */  
	public static final String SAVEBUTTON_HELPBLOCK_MAPPING_KEY = "frmGoodsPledgeSaveButtonHelpBlock";

    
	/** Entity Id */
	private Long id;

	/** localization messages are bound to a particular view allowing the messages for a distinct view to be loaded*/
	private Long viewId;

	
    /** id of a parent object used when adding objects via JSON enabled restful web services */
    private Long parentObjectId;
    
    
    /** the the newLocale setting which is the locale currently being updated */
    private Long newLocale;

    /** the title as displayed in the browser tab */
    private String formTitle;

    /** the page title as displayed at the top of the page */
    private String viewTitle;
    
    /** the form sub header as displayed below the form header */
	private String formSubHeader;
    
    
    
	/** the reference to the foreign associated RegisterOfPledges **/
	private RegisterOfPledges registerOfPledges;
    
    private String pledgedGoodsLabelMessageKey;
    private String pledgedGoodsLabel;

    private String pledgedGoodsPlaceHolderMessageKey;
    private String pledgedGoodsPlaceHolder;
    
    private String pledgedGoodsHelpTextMessageKey;
    private String pledgedGoodsHelpText;
    
    private String pledgedGoodsTooltipMessageKey;
    private String pledgedGoodsTooltip;
    
    private String additionalInformationLabelMessageKey;
    private String additionalInformationLabel;

    private String additionalInformationPlaceHolderMessageKey;
    private String additionalInformationPlaceHolder;
    
    private String additionalInformationHelpTextMessageKey;
    private String additionalInformationHelpText;
    
    private String additionalInformationTooltipMessageKey;
    private String additionalInformationTooltip;
    
    private String itemSizeLabelMessageKey;
    private String itemSizeLabel;

    private String itemSizePlaceHolderMessageKey;
    private String itemSizePlaceHolder;
    
    private String itemSizeHelpTextMessageKey;
    private String itemSizeHelpText;
    
    private String itemSizeTooltipMessageKey;
    private String itemSizeTooltip;
    
    private String goodsConditionLabelMessageKey;
    private String goodsConditionLabel;

    private String goodsConditionPlaceHolderMessageKey;
    private String goodsConditionPlaceHolder;
    
    private String goodsConditionHelpTextMessageKey;
    private String goodsConditionHelpText;
    
    private String goodsConditionTooltipMessageKey;
    private String goodsConditionTooltip;
    
    private String numberOfItemsLabelMessageKey;
    private String numberOfItemsLabel;

    private String numberOfItemsPlaceHolderMessageKey;
    private String numberOfItemsPlaceHolder;
    
    private String numberOfItemsHelpTextMessageKey;
    private String numberOfItemsHelpText;
    
    private String numberOfItemsTooltipMessageKey;
    private String numberOfItemsTooltip;
    
    private String saveButtonLabelMessageKey;
    private String saveButtonLabel;

    private String saveButtonPlaceHolderMessageKey;
    private String saveButtonPlaceHolder;
    
    private String saveButtonHelpTextMessageKey;
    private String saveButtonHelpText;
    
    private String saveButtonTooltipMessageKey;
    private String saveButtonTooltip;

    
    /**
     * Default Constructor for the GoodsPledgeTranslationBackingBean
     */
    public GoodsPledgeTranslationBackingBeanImpl()
    {
    	setViewId(GoodsPledgeTranslationBackingBeanImpl.VIEW_ID);
		pledgedGoodsLabelMessageKey = new String();  
		pledgedGoodsLabel = new String();
		pledgedGoodsPlaceHolderMessageKey = new String();
		pledgedGoodsPlaceHolder = new String();
		pledgedGoodsHelpTextMessageKey = new String();
		pledgedGoodsHelpText = new String();
		pledgedGoodsTooltipMessageKey = new String();
		pledgedGoodsTooltip = new String();
		additionalInformationLabelMessageKey = new String();  
		additionalInformationLabel = new String();
		additionalInformationPlaceHolderMessageKey = new String();
		additionalInformationPlaceHolder = new String();
		additionalInformationHelpTextMessageKey = new String();
		additionalInformationHelpText = new String();
		additionalInformationTooltipMessageKey = new String();
		additionalInformationTooltip = new String();
		itemSizeLabelMessageKey = new String();  
		itemSizeLabel = new String();
		itemSizePlaceHolderMessageKey = new String();
		itemSizePlaceHolder = new String();
		itemSizeHelpTextMessageKey = new String();
		itemSizeHelpText = new String();
		itemSizeTooltipMessageKey = new String();
		itemSizeTooltip = new String();
		goodsConditionLabelMessageKey = new String();  
		goodsConditionLabel = new String();
		goodsConditionPlaceHolderMessageKey = new String();
		goodsConditionPlaceHolder = new String();
		goodsConditionHelpTextMessageKey = new String();
		goodsConditionHelpText = new String();
		goodsConditionTooltipMessageKey = new String();
		goodsConditionTooltip = new String();
		numberOfItemsLabelMessageKey = new String();  
		numberOfItemsLabel = new String();
		numberOfItemsPlaceHolderMessageKey = new String();
		numberOfItemsPlaceHolder = new String();
		numberOfItemsHelpTextMessageKey = new String();
		numberOfItemsHelpText = new String();
		numberOfItemsTooltipMessageKey = new String();
		numberOfItemsTooltip = new String();
		saveButtonLabelMessageKey = new String();  
		saveButtonLabel = new String();
		saveButtonPlaceHolderMessageKey = new String();
		saveButtonPlaceHolder = new String();
		saveButtonHelpTextMessageKey = new String();
		saveButtonHelpText = new String();
		saveButtonTooltipMessageKey = new String();
		saveButtonTooltip = new String();

    }
    
    /*
     * Returns the Id for the underlying database table record
     */
	public Long getId()
	{
        return id;
    }

    /*
     * Sets the Id. This allows front-end forms to bind the id property
     */
	public void setId(Long id)
	{
        this.id = id;
    }
    
    /*
     * Returns the viewId to which the current translations are bound
     */
	public Long getViewId()
	{
        return viewId;
    }

    /*
     * Sets the viewId. This allows the page translations to be bound to a view
     */
	public void setViewId(Long viewId)
	{
        this.viewId = viewId;
    }
    

    /*
     * Returns the parentObjectId when this object has been populated via a restful webservice JSON mapping
     */
	public Long getParentObjectId()
	{
        return parentObjectId;
    }

    /*
     * Sets the parentObjectId. This allows restful web services to bind the parentId property when adding a new record.
     */
	public void setParentObjectId(Long parentObjectId)
	{
        this.parentObjectId = parentObjectId;
    }
    
    /*
     * Returns the newLocale setting which is the locale currently being updated
     */
	public Long getNewLocale()
	{
        return newLocale;
    }

    /*
     * Sets the the newLocale setting which is the locale currently being updated
     */
	public void setNewLocale(Long newLocale)
	{
        this.newLocale = newLocale;
    }

    /*
     * Returns the page title as displayed in the browser tab
     */
	public String getFormTitle()
	{
        return formTitle;
    }

    /*
     * Sets the page title as displayed in the browser tab
     */
	public void setFormTitle(String formTitle)
	{
        this.formTitle = formTitle;
    }
    
    
    /*
     * Returns the page title as displayed at the top of the page
     */
	public String getViewTitle()
	{
        return viewTitle;
    }

    /*
     * Sets the page title as displayed at the top of the page
     */
	public void setViewTitle(String viewTitle)
	{
        this.viewTitle = viewTitle;
    }
    

    /*
     * Returns the form sub header as displayed below the form header
     */
	public String getFormSubHeader()
	{
        return formSubHeader;
    }

    /*
     * Sets the form sub header as displayed below the form header
     */
	public void setFormSubHeader(String formSubHeader)
	{
        this.formSubHeader = formSubHeader;
    }
    

	
    
    
    /**
     * Sets the pledgedGoodsLabelMessageKey
     * @param pledgedGoodsLabelMessageKey
     */
    public void setPledgedGoodsLabelMessageKey(String pledgedGoodsLabelMessageKey)
    {
      this.pledgedGoodsLabelMessageKey = pledgedGoodsLabelMessageKey;
    }

    /**
     * Returns the pledgedGoodsLabelMessageKey
     * @return the pledgedGoodsLabelMessageKey
     */
    public String getPledgedGoodsLabelMessageKey()
    {
      return pledgedGoodsLabelMessageKey;
    }

    /**
     * Sets the pledgedGoodsLabel
     * @param pledgedGoodsLabel
     */
    public void setPledgedGoodsLabel(String pledgedGoodsLabel)
    {
      this.pledgedGoodsLabel = pledgedGoodsLabel;
    }

    /**
     * Returns the pledgedGoodsLabel
     * @return the pledgedGoodsLabel
     */
    public String getPledgedGoodsLabel()
    {
      return pledgedGoodsLabel;
    }
    
    
    /**
     * Sets the pledgedGoodsPlaceHolderMessageKey
     * @param pledgedGoodsPlaceHolderMessageKey
     */
    public void setPledgedGoodsPlaceHolderMessageKey(String pledgedGoodsPlaceHolderMessageKey)
    {
      this.pledgedGoodsPlaceHolderMessageKey = pledgedGoodsPlaceHolderMessageKey;
    }

    /**
     * Returns the pledgedGoodsPlaceHolderMessageKey
     * @return the pledgedGoodsPlaceHolderMessageKey
     */
    public String getPledgedGoodsPlaceHolderMessageKey()
    {
      return pledgedGoodsPlaceHolderMessageKey;
    }

    /**
     * Sets the pledgedGoodsPlaceHolder
     * @param pledgedGoodsPlaceHolder
     */
    public void setPledgedGoodsPlaceHolder(String pledgedGoodsPlaceHolder)
    {
      this.pledgedGoodsPlaceHolder = pledgedGoodsPlaceHolder;
    }

    /**
     * Returns the pledgedGoodsPlaceHolder
     * @return the pledgedGoodsPlaceHolder
     */
    public String getPledgedGoodsPlaceHolder()
    {
      return pledgedGoodsPlaceHolder;
    }    
    
    /**
     * Sets the pledgedGoodsHelpTextMessageKey
     * @param pledgedGoodsHelpTextMessageKey
     */
    public void setPledgedGoodsHelpTextMessageKey(String pledgedGoodsHelpTextMessageKey)
    {
      this.pledgedGoodsHelpTextMessageKey = pledgedGoodsHelpTextMessageKey;
    }

    /**
     * Returns the pledgedGoodsHelpTextMessageKey
     * @return the pledgedGoodsHelpTextMessageKey
     */
    public String getPledgedGoodsHelpTextMessageKey()
    {
      return pledgedGoodsHelpTextMessageKey;
    }

    /**
     * Sets the pledgedGoodsHelpText
     * @param pledgedGoodsHelpText
     */
    public void setPledgedGoodsHelpText(String pledgedGoodsHelpText)
    {
      this.pledgedGoodsHelpText = pledgedGoodsHelpText;
    }

    /**
     * Returns the pledgedGoodsHelpText
     * @return the pledgedGoodsHelpText
     */
    public String getPledgedGoodsHelpText()
    {
      return pledgedGoodsHelpText;
    }    
    
    /**
     * Sets the pledgedGoodsTooltipMessageKey
     * @param pledgedGoodsTooltipMessageKey
     */
    public void setPledgedGoodsTooltipMessageKey(String pledgedGoodsTooltipMessageKey)
    {
      this.pledgedGoodsTooltipMessageKey = pledgedGoodsTooltipMessageKey;
    }

    /**
     * Returns the pledgedGoodsTooltipMessageKey
     * @return the pledgedGoodsTooltipMessageKey
     */
    public String getPledgedGoodsTooltipMessageKey()
    {
      return pledgedGoodsTooltipMessageKey;
    }

    /**
     * Sets the pledgedGoodsTooltip
     * @param pledgedGoodsTooltip
     */
    public void setPledgedGoodsTooltip(String pledgedGoodsTooltip)
    {
      this.pledgedGoodsTooltip = pledgedGoodsTooltip;
    }

    /**
     * Returns the pledgedGoodsTooltip
     * @return the pledgedGoodsTooltip
     */
    public String getPledgedGoodsTooltip()
    {
      return pledgedGoodsTooltip;
    }    

    
    /**
     * Sets the additionalInformationLabelMessageKey
     * @param additionalInformationLabelMessageKey
     */
    public void setAdditionalInformationLabelMessageKey(String additionalInformationLabelMessageKey)
    {
      this.additionalInformationLabelMessageKey = additionalInformationLabelMessageKey;
    }

    /**
     * Returns the additionalInformationLabelMessageKey
     * @return the additionalInformationLabelMessageKey
     */
    public String getAdditionalInformationLabelMessageKey()
    {
      return additionalInformationLabelMessageKey;
    }

    /**
     * Sets the additionalInformationLabel
     * @param additionalInformationLabel
     */
    public void setAdditionalInformationLabel(String additionalInformationLabel)
    {
      this.additionalInformationLabel = additionalInformationLabel;
    }

    /**
     * Returns the additionalInformationLabel
     * @return the additionalInformationLabel
     */
    public String getAdditionalInformationLabel()
    {
      return additionalInformationLabel;
    }
    
    
    /**
     * Sets the additionalInformationPlaceHolderMessageKey
     * @param additionalInformationPlaceHolderMessageKey
     */
    public void setAdditionalInformationPlaceHolderMessageKey(String additionalInformationPlaceHolderMessageKey)
    {
      this.additionalInformationPlaceHolderMessageKey = additionalInformationPlaceHolderMessageKey;
    }

    /**
     * Returns the additionalInformationPlaceHolderMessageKey
     * @return the additionalInformationPlaceHolderMessageKey
     */
    public String getAdditionalInformationPlaceHolderMessageKey()
    {
      return additionalInformationPlaceHolderMessageKey;
    }

    /**
     * Sets the additionalInformationPlaceHolder
     * @param additionalInformationPlaceHolder
     */
    public void setAdditionalInformationPlaceHolder(String additionalInformationPlaceHolder)
    {
      this.additionalInformationPlaceHolder = additionalInformationPlaceHolder;
    }

    /**
     * Returns the additionalInformationPlaceHolder
     * @return the additionalInformationPlaceHolder
     */
    public String getAdditionalInformationPlaceHolder()
    {
      return additionalInformationPlaceHolder;
    }    
    
    /**
     * Sets the additionalInformationHelpTextMessageKey
     * @param additionalInformationHelpTextMessageKey
     */
    public void setAdditionalInformationHelpTextMessageKey(String additionalInformationHelpTextMessageKey)
    {
      this.additionalInformationHelpTextMessageKey = additionalInformationHelpTextMessageKey;
    }

    /**
     * Returns the additionalInformationHelpTextMessageKey
     * @return the additionalInformationHelpTextMessageKey
     */
    public String getAdditionalInformationHelpTextMessageKey()
    {
      return additionalInformationHelpTextMessageKey;
    }

    /**
     * Sets the additionalInformationHelpText
     * @param additionalInformationHelpText
     */
    public void setAdditionalInformationHelpText(String additionalInformationHelpText)
    {
      this.additionalInformationHelpText = additionalInformationHelpText;
    }

    /**
     * Returns the additionalInformationHelpText
     * @return the additionalInformationHelpText
     */
    public String getAdditionalInformationHelpText()
    {
      return additionalInformationHelpText;
    }    
    
    /**
     * Sets the additionalInformationTooltipMessageKey
     * @param additionalInformationTooltipMessageKey
     */
    public void setAdditionalInformationTooltipMessageKey(String additionalInformationTooltipMessageKey)
    {
      this.additionalInformationTooltipMessageKey = additionalInformationTooltipMessageKey;
    }

    /**
     * Returns the additionalInformationTooltipMessageKey
     * @return the additionalInformationTooltipMessageKey
     */
    public String getAdditionalInformationTooltipMessageKey()
    {
      return additionalInformationTooltipMessageKey;
    }

    /**
     * Sets the additionalInformationTooltip
     * @param additionalInformationTooltip
     */
    public void setAdditionalInformationTooltip(String additionalInformationTooltip)
    {
      this.additionalInformationTooltip = additionalInformationTooltip;
    }

    /**
     * Returns the additionalInformationTooltip
     * @return the additionalInformationTooltip
     */
    public String getAdditionalInformationTooltip()
    {
      return additionalInformationTooltip;
    }    

    
    /**
     * Sets the itemSizeLabelMessageKey
     * @param itemSizeLabelMessageKey
     */
    public void setItemSizeLabelMessageKey(String itemSizeLabelMessageKey)
    {
      this.itemSizeLabelMessageKey = itemSizeLabelMessageKey;
    }

    /**
     * Returns the itemSizeLabelMessageKey
     * @return the itemSizeLabelMessageKey
     */
    public String getItemSizeLabelMessageKey()
    {
      return itemSizeLabelMessageKey;
    }

    /**
     * Sets the itemSizeLabel
     * @param itemSizeLabel
     */
    public void setItemSizeLabel(String itemSizeLabel)
    {
      this.itemSizeLabel = itemSizeLabel;
    }

    /**
     * Returns the itemSizeLabel
     * @return the itemSizeLabel
     */
    public String getItemSizeLabel()
    {
      return itemSizeLabel;
    }
    
    
    /**
     * Sets the itemSizePlaceHolderMessageKey
     * @param itemSizePlaceHolderMessageKey
     */
    public void setItemSizePlaceHolderMessageKey(String itemSizePlaceHolderMessageKey)
    {
      this.itemSizePlaceHolderMessageKey = itemSizePlaceHolderMessageKey;
    }

    /**
     * Returns the itemSizePlaceHolderMessageKey
     * @return the itemSizePlaceHolderMessageKey
     */
    public String getItemSizePlaceHolderMessageKey()
    {
      return itemSizePlaceHolderMessageKey;
    }

    /**
     * Sets the itemSizePlaceHolder
     * @param itemSizePlaceHolder
     */
    public void setItemSizePlaceHolder(String itemSizePlaceHolder)
    {
      this.itemSizePlaceHolder = itemSizePlaceHolder;
    }

    /**
     * Returns the itemSizePlaceHolder
     * @return the itemSizePlaceHolder
     */
    public String getItemSizePlaceHolder()
    {
      return itemSizePlaceHolder;
    }    
    
    /**
     * Sets the itemSizeHelpTextMessageKey
     * @param itemSizeHelpTextMessageKey
     */
    public void setItemSizeHelpTextMessageKey(String itemSizeHelpTextMessageKey)
    {
      this.itemSizeHelpTextMessageKey = itemSizeHelpTextMessageKey;
    }

    /**
     * Returns the itemSizeHelpTextMessageKey
     * @return the itemSizeHelpTextMessageKey
     */
    public String getItemSizeHelpTextMessageKey()
    {
      return itemSizeHelpTextMessageKey;
    }

    /**
     * Sets the itemSizeHelpText
     * @param itemSizeHelpText
     */
    public void setItemSizeHelpText(String itemSizeHelpText)
    {
      this.itemSizeHelpText = itemSizeHelpText;
    }

    /**
     * Returns the itemSizeHelpText
     * @return the itemSizeHelpText
     */
    public String getItemSizeHelpText()
    {
      return itemSizeHelpText;
    }    
    
    /**
     * Sets the itemSizeTooltipMessageKey
     * @param itemSizeTooltipMessageKey
     */
    public void setItemSizeTooltipMessageKey(String itemSizeTooltipMessageKey)
    {
      this.itemSizeTooltipMessageKey = itemSizeTooltipMessageKey;
    }

    /**
     * Returns the itemSizeTooltipMessageKey
     * @return the itemSizeTooltipMessageKey
     */
    public String getItemSizeTooltipMessageKey()
    {
      return itemSizeTooltipMessageKey;
    }

    /**
     * Sets the itemSizeTooltip
     * @param itemSizeTooltip
     */
    public void setItemSizeTooltip(String itemSizeTooltip)
    {
      this.itemSizeTooltip = itemSizeTooltip;
    }

    /**
     * Returns the itemSizeTooltip
     * @return the itemSizeTooltip
     */
    public String getItemSizeTooltip()
    {
      return itemSizeTooltip;
    }    

    
    /**
     * Sets the goodsConditionLabelMessageKey
     * @param goodsConditionLabelMessageKey
     */
    public void setGoodsConditionLabelMessageKey(String goodsConditionLabelMessageKey)
    {
      this.goodsConditionLabelMessageKey = goodsConditionLabelMessageKey;
    }

    /**
     * Returns the goodsConditionLabelMessageKey
     * @return the goodsConditionLabelMessageKey
     */
    public String getGoodsConditionLabelMessageKey()
    {
      return goodsConditionLabelMessageKey;
    }

    /**
     * Sets the goodsConditionLabel
     * @param goodsConditionLabel
     */
    public void setGoodsConditionLabel(String goodsConditionLabel)
    {
      this.goodsConditionLabel = goodsConditionLabel;
    }

    /**
     * Returns the goodsConditionLabel
     * @return the goodsConditionLabel
     */
    public String getGoodsConditionLabel()
    {
      return goodsConditionLabel;
    }
    
    
    /**
     * Sets the goodsConditionPlaceHolderMessageKey
     * @param goodsConditionPlaceHolderMessageKey
     */
    public void setGoodsConditionPlaceHolderMessageKey(String goodsConditionPlaceHolderMessageKey)
    {
      this.goodsConditionPlaceHolderMessageKey = goodsConditionPlaceHolderMessageKey;
    }

    /**
     * Returns the goodsConditionPlaceHolderMessageKey
     * @return the goodsConditionPlaceHolderMessageKey
     */
    public String getGoodsConditionPlaceHolderMessageKey()
    {
      return goodsConditionPlaceHolderMessageKey;
    }

    /**
     * Sets the goodsConditionPlaceHolder
     * @param goodsConditionPlaceHolder
     */
    public void setGoodsConditionPlaceHolder(String goodsConditionPlaceHolder)
    {
      this.goodsConditionPlaceHolder = goodsConditionPlaceHolder;
    }

    /**
     * Returns the goodsConditionPlaceHolder
     * @return the goodsConditionPlaceHolder
     */
    public String getGoodsConditionPlaceHolder()
    {
      return goodsConditionPlaceHolder;
    }    
    
    /**
     * Sets the goodsConditionHelpTextMessageKey
     * @param goodsConditionHelpTextMessageKey
     */
    public void setGoodsConditionHelpTextMessageKey(String goodsConditionHelpTextMessageKey)
    {
      this.goodsConditionHelpTextMessageKey = goodsConditionHelpTextMessageKey;
    }

    /**
     * Returns the goodsConditionHelpTextMessageKey
     * @return the goodsConditionHelpTextMessageKey
     */
    public String getGoodsConditionHelpTextMessageKey()
    {
      return goodsConditionHelpTextMessageKey;
    }

    /**
     * Sets the goodsConditionHelpText
     * @param goodsConditionHelpText
     */
    public void setGoodsConditionHelpText(String goodsConditionHelpText)
    {
      this.goodsConditionHelpText = goodsConditionHelpText;
    }

    /**
     * Returns the goodsConditionHelpText
     * @return the goodsConditionHelpText
     */
    public String getGoodsConditionHelpText()
    {
      return goodsConditionHelpText;
    }    
    
    /**
     * Sets the goodsConditionTooltipMessageKey
     * @param goodsConditionTooltipMessageKey
     */
    public void setGoodsConditionTooltipMessageKey(String goodsConditionTooltipMessageKey)
    {
      this.goodsConditionTooltipMessageKey = goodsConditionTooltipMessageKey;
    }

    /**
     * Returns the goodsConditionTooltipMessageKey
     * @return the goodsConditionTooltipMessageKey
     */
    public String getGoodsConditionTooltipMessageKey()
    {
      return goodsConditionTooltipMessageKey;
    }

    /**
     * Sets the goodsConditionTooltip
     * @param goodsConditionTooltip
     */
    public void setGoodsConditionTooltip(String goodsConditionTooltip)
    {
      this.goodsConditionTooltip = goodsConditionTooltip;
    }

    /**
     * Returns the goodsConditionTooltip
     * @return the goodsConditionTooltip
     */
    public String getGoodsConditionTooltip()
    {
      return goodsConditionTooltip;
    }    

    
    /**
     * Sets the numberOfItemsLabelMessageKey
     * @param numberOfItemsLabelMessageKey
     */
    public void setNumberOfItemsLabelMessageKey(String numberOfItemsLabelMessageKey)
    {
      this.numberOfItemsLabelMessageKey = numberOfItemsLabelMessageKey;
    }

    /**
     * Returns the numberOfItemsLabelMessageKey
     * @return the numberOfItemsLabelMessageKey
     */
    public String getNumberOfItemsLabelMessageKey()
    {
      return numberOfItemsLabelMessageKey;
    }

    /**
     * Sets the numberOfItemsLabel
     * @param numberOfItemsLabel
     */
    public void setNumberOfItemsLabel(String numberOfItemsLabel)
    {
      this.numberOfItemsLabel = numberOfItemsLabel;
    }

    /**
     * Returns the numberOfItemsLabel
     * @return the numberOfItemsLabel
     */
    public String getNumberOfItemsLabel()
    {
      return numberOfItemsLabel;
    }
    
    
    /**
     * Sets the numberOfItemsPlaceHolderMessageKey
     * @param numberOfItemsPlaceHolderMessageKey
     */
    public void setNumberOfItemsPlaceHolderMessageKey(String numberOfItemsPlaceHolderMessageKey)
    {
      this.numberOfItemsPlaceHolderMessageKey = numberOfItemsPlaceHolderMessageKey;
    }

    /**
     * Returns the numberOfItemsPlaceHolderMessageKey
     * @return the numberOfItemsPlaceHolderMessageKey
     */
    public String getNumberOfItemsPlaceHolderMessageKey()
    {
      return numberOfItemsPlaceHolderMessageKey;
    }

    /**
     * Sets the numberOfItemsPlaceHolder
     * @param numberOfItemsPlaceHolder
     */
    public void setNumberOfItemsPlaceHolder(String numberOfItemsPlaceHolder)
    {
      this.numberOfItemsPlaceHolder = numberOfItemsPlaceHolder;
    }

    /**
     * Returns the numberOfItemsPlaceHolder
     * @return the numberOfItemsPlaceHolder
     */
    public String getNumberOfItemsPlaceHolder()
    {
      return numberOfItemsPlaceHolder;
    }    
    
    /**
     * Sets the numberOfItemsHelpTextMessageKey
     * @param numberOfItemsHelpTextMessageKey
     */
    public void setNumberOfItemsHelpTextMessageKey(String numberOfItemsHelpTextMessageKey)
    {
      this.numberOfItemsHelpTextMessageKey = numberOfItemsHelpTextMessageKey;
    }

    /**
     * Returns the numberOfItemsHelpTextMessageKey
     * @return the numberOfItemsHelpTextMessageKey
     */
    public String getNumberOfItemsHelpTextMessageKey()
    {
      return numberOfItemsHelpTextMessageKey;
    }

    /**
     * Sets the numberOfItemsHelpText
     * @param numberOfItemsHelpText
     */
    public void setNumberOfItemsHelpText(String numberOfItemsHelpText)
    {
      this.numberOfItemsHelpText = numberOfItemsHelpText;
    }

    /**
     * Returns the numberOfItemsHelpText
     * @return the numberOfItemsHelpText
     */
    public String getNumberOfItemsHelpText()
    {
      return numberOfItemsHelpText;
    }    
    
    /**
     * Sets the numberOfItemsTooltipMessageKey
     * @param numberOfItemsTooltipMessageKey
     */
    public void setNumberOfItemsTooltipMessageKey(String numberOfItemsTooltipMessageKey)
    {
      this.numberOfItemsTooltipMessageKey = numberOfItemsTooltipMessageKey;
    }

    /**
     * Returns the numberOfItemsTooltipMessageKey
     * @return the numberOfItemsTooltipMessageKey
     */
    public String getNumberOfItemsTooltipMessageKey()
    {
      return numberOfItemsTooltipMessageKey;
    }

    /**
     * Sets the numberOfItemsTooltip
     * @param numberOfItemsTooltip
     */
    public void setNumberOfItemsTooltip(String numberOfItemsTooltip)
    {
      this.numberOfItemsTooltip = numberOfItemsTooltip;
    }

    /**
     * Returns the numberOfItemsTooltip
     * @return the numberOfItemsTooltip
     */
    public String getNumberOfItemsTooltip()
    {
      return numberOfItemsTooltip;
    }    

    
    /**
     * Sets the saveButtonLabelMessageKey
     * @param saveButtonLabelMessageKey
     */
    public void setSaveButtonLabelMessageKey(String saveButtonLabelMessageKey)
    {
      this.saveButtonLabelMessageKey = saveButtonLabelMessageKey;
    }

    /**
     * Returns the saveButtonLabelMessageKey
     * @return the saveButtonLabelMessageKey
     */
    public String getSaveButtonLabelMessageKey()
    {
      return saveButtonLabelMessageKey;
    }

    /**
     * Sets the saveButtonLabel
     * @param saveButtonLabel
     */
    public void setSaveButtonLabel(String saveButtonLabel)
    {
      this.saveButtonLabel = saveButtonLabel;
    }

    /**
     * Returns the saveButtonLabel
     * @return the saveButtonLabel
     */
    public String getSaveButtonLabel()
    {
      return saveButtonLabel;
    }
    
    
    /**
     * Sets the saveButtonPlaceHolderMessageKey
     * @param saveButtonPlaceHolderMessageKey
     */
    public void setSaveButtonPlaceHolderMessageKey(String saveButtonPlaceHolderMessageKey)
    {
      this.saveButtonPlaceHolderMessageKey = saveButtonPlaceHolderMessageKey;
    }

    /**
     * Returns the saveButtonPlaceHolderMessageKey
     * @return the saveButtonPlaceHolderMessageKey
     */
    public String getSaveButtonPlaceHolderMessageKey()
    {
      return saveButtonPlaceHolderMessageKey;
    }

    /**
     * Sets the saveButtonPlaceHolder
     * @param saveButtonPlaceHolder
     */
    public void setSaveButtonPlaceHolder(String saveButtonPlaceHolder)
    {
      this.saveButtonPlaceHolder = saveButtonPlaceHolder;
    }

    /**
     * Returns the saveButtonPlaceHolder
     * @return the saveButtonPlaceHolder
     */
    public String getSaveButtonPlaceHolder()
    {
      return saveButtonPlaceHolder;
    }    
    
    /**
     * Sets the saveButtonHelpTextMessageKey
     * @param saveButtonHelpTextMessageKey
     */
    public void setSaveButtonHelpTextMessageKey(String saveButtonHelpTextMessageKey)
    {
      this.saveButtonHelpTextMessageKey = saveButtonHelpTextMessageKey;
    }

    /**
     * Returns the saveButtonHelpTextMessageKey
     * @return the saveButtonHelpTextMessageKey
     */
    public String getSaveButtonHelpTextMessageKey()
    {
      return saveButtonHelpTextMessageKey;
    }

    /**
     * Sets the saveButtonHelpText
     * @param saveButtonHelpText
     */
    public void setSaveButtonHelpText(String saveButtonHelpText)
    {
      this.saveButtonHelpText = saveButtonHelpText;
    }

    /**
     * Returns the saveButtonHelpText
     * @return the saveButtonHelpText
     */
    public String getSaveButtonHelpText()
    {
      return saveButtonHelpText;
    }    
    
    /**
     * Sets the saveButtonTooltipMessageKey
     * @param saveButtonTooltipMessageKey
     */
    public void setSaveButtonTooltipMessageKey(String saveButtonTooltipMessageKey)
    {
      this.saveButtonTooltipMessageKey = saveButtonTooltipMessageKey;
    }

    /**
     * Returns the saveButtonTooltipMessageKey
     * @return the saveButtonTooltipMessageKey
     */
    public String getSaveButtonTooltipMessageKey()
    {
      return saveButtonTooltipMessageKey;
    }

    /**
     * Sets the saveButtonTooltip
     * @param saveButtonTooltip
     */
    public void setSaveButtonTooltip(String saveButtonTooltip)
    {
      this.saveButtonTooltip = saveButtonTooltip;
    }

    /**
     * Returns the saveButtonTooltip
     * @return the saveButtonTooltip
     */
    public String getSaveButtonTooltip()
    {
      return saveButtonTooltip;
    }    


    /**
     * Checks for a newly created entity object
     * @return true if this is a newly created entity object meaning that it has not yet been persisted, otherwise false
     */
	public boolean isNew() {
		return (this.id == null);
	}
	
    
    
/*     @Override
     public String toString(){
     // TODO: To be implemented
    	return "TODO: to be done";
     }
*/     
}
    
    
    

