package org.volunteertech.pledges.localisation.service;
import com.netgrains.security.AuthorisationException;
import com.netgrains.security.InvalidUserIDException;
import org.volunteertech.pledges.localisation.dao.MessageResource;
import org.volunteertech.pledges.localisation.business.MessageResourceBo;
import org.volunteertech.pledges.localisation.dao.MessageResourceFilter;
import org.volunteertech.pledges.localisation.dao.MessageResourceHistory;
import org.volunteertech.pledges.localisation.dao.MessageResourceLoadException;
import org.volunteertech.pledges.localisation.dao.MessageResourceSaveException;
import java.util.List;
import java.util.Set;
import java.util.Date;
import java.math.BigDecimal;
import java.util.Locale;


import org.volunteertech.pledges.reference.service.ReferenceService;
  
import org.volunteertech.pledges.main.localisation.DatabaseDrivenMessageSource;
  


/**
 * The model to hold localisation messages
 * This Interface has been generated by the XSLT processor from the meta data and represents the
 * interface of the Service  Layer Object for the MessageResource entity. A Business Object
 * is provided in order to provide a seperation from the Data Access implementation. 
 * <P> 
 * It is essential that methods added to this class are given JavaDoc comments to allow
 * documentation to be generated. For a description of JavaDoc refer to The JavaDoc documentation.
 * A link is provided below.
 * <P>
 * @author Michael O'Connor
 * @version $Revision$
 * Date: * $Date$
 * @see <a href="http://java.sun.com/j2se/javadoc/writingdoccomments/index.html">>JavaDoc Documentation</a> 
 * Change Log
 * ----------
 * $Log$
 *
 */
public interface MessageResourceService
{
    
	/**
	 * Sets the reference Service to perform a user roles lookup
	 */
	public void setReferenceService(ReferenceService referenceService);
	
	/**
	 * Returns a reference to reference Service.
	 */
	public ReferenceService getReferenceService();
	  
	/**
	 * Sets the reference to the MessageSource required to perform a user roles lookup
	 */
	public void setMessageSource(DatabaseDrivenMessageSource messageSource);
	
	/**
	 * Returns a reference to the MessageSource instance.
	 */
	public DatabaseDrivenMessageSource getMessageSource();
  
    
    /**
     * Sets the required Business Object (BO)
     * @param messageResourceBo the messageResourceBo used to access the messageResource entity
     * and it's associations.
     */
    public void setMessageResourceBo(MessageResourceBo messageResourceBo);
    

    /**
     * Returns the required Business Object (BO)
     * @return the MessageResourceBo used to access the messageResource entity
     * and it's associations.
     */
    public MessageResourceBo getMessageResourceBo();
    
    

    /**
     * Loads a MessageResource object based on the MESSAGERESOURCEID column
     * @param MESSAGERESOURCEID the primary key for the underlying record.
     * @param userID the userID is checked for authorisation to view the record
     * @ return a MessageResource object matching the parameter or null if none can be found. The
     * method also returns null if the parameter is null.
     */
    public MessageResource load(Long messageResourceID, Long loggedInUserId) throws MessageResourceLoadException, AuthorisationException, InvalidUserIDException;
    
    
      
    /**
     * Load a MessageResource object using the Locale and messageKey as search parameters.
     * @return a MessageResource object.
     */
    public MessageResource loadMessageResourceForLocale(String messageKey, String locale) throws MessageResourceLoadException, AuthorisationException, InvalidUserIDException;

    /**
     * Returns a reolved locale specific message from the underlying message resource manager
     * @param messageKey the message key
     * @param args array of arguments that will be filled in for params within the message (params look like "{0}", "{1,date}", "{2,time}" within a message), or null if none.
     * @param locale the specific locale to which to resolve the message 
     */
    public String getMessage(String messageKey, Object[] args, Locale locale);
    
    /**
     * Returns a resolved locale specific message from the underlying message resource manager
     * @param referenceId a referenceId that is looked up againt the reference table to resolve the message key
     * @param args array of arguments that will be filled in for params within the message (params look like "{0}", "{1,date}", "{2,time}" within a message), or null if none.
     * @param locale the specific locale to which to resolve the message 
     */
    public String getMessage(Long referenceId, Object[] args, Locale locale);
      

    /**
     * Load all existing MessageResource objects. 
     * @return List a List of MessageResource objects.
     */
    public List<MessageResource> listMessageResource();
    
    
    /**
     * Returns a <code>List</code> of MessageResource objects that have a matching messageKey
     * @return List a List of MessageResource objects that match the messageKey property given as parameter.
     * @param messageKey the messageKey on which to match the required records.
     */
    public List<MessageResource> listMessageResourceByMessageKey(String messageKey);

    /**
     * Returns a <code>List</code> of MessageResource objects that have a matching locale
     * @return List a List of MessageResource objects that match the locale property given as parameter.
     * @param locale the locale on which to match the required records.
     */
    public List<MessageResource> listMessageResourceByLocale(String locale);

    /**
     * Returns a <code>List</code> of MessageResource objects that have a matching localeReferenceId
     * @return List a List of MessageResource objects that match the localeReferenceId property given as parameter.
     * @param localeReferenceId the localeReferenceId on which to match the required records.
     */
    public List<MessageResource> listMessageResourceByLocaleReferenceId(Long localeReferenceId);

    /**
     * Returns a <code>List</code> of MessageResource objects that have a matching message
     * @return List a List of MessageResource objects that match the message property given as parameter.
     * @param message the message on which to match the required records.
     */
    public List<MessageResource> listMessageResourceByMessage(String message);

    
    
    /**
     * Load existing MessageResource objects from the database that have a createdByID column
     * that matches the userId parameter.
     * @return List a List of MessageResource objects that match the userId parameter.
     */
    public List<MessageResource> listMessageResourceByCreatedById(Long userId);
    
    
    /**
     * Load all existing MessageResourceHistory objects for a particular MessageResource.
     * The <code>List</code> of MessageResourceHistory objects contains all of the changes that have been made to the
     * MessageResource object identified by the messageResource parameter'
     * @return List a List of MessageResourceHistory objects.
     */
    public List<MessageResourceHistory> listMessageResourceHistory(Long messageResource) throws Exception;
    
    
    
    /**
     * Either updates an existing entry in the MESSAGERESOURCE table or adds a new entry if one does not exist.
     *
     * @param userId the userId of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @throws MessageResourceLoadException if the existing record cannot be loaded
     * @throws MessageResourceSaveException if there is an issue populating or saving the updated object
     * @throws AuthorisationException if the user is not authorised to update the object
     * @throws InvalidUserIDException if the userID passed as parameter is not valid
     */
    public void storeMessageResource(MessageResource messageResource, Long userId)
        throws MessageResourceSaveException, MessageResourceLoadException, AuthorisationException, InvalidUserIDException;
    
    
    /**
     * Loads a MessageResourceFilter object based on the participantID of the currently logged in user
     * @param userId the userId is checked for authorisation to view the record. It is also the key to load a against the createdByID
     * column of the underlying record. There should only ever be one or zero filter records per MessageResource.
     * @ return a MessageResourceFilter object matching the parameter or a newly constructed, empty object if none can be found
     */
    public MessageResourceFilter loadMessageResourceFilter(Long userId) throws MessageResourceLoadException, AuthorisationException, InvalidUserIDException;


    
    /**
     * Creates a new entry in the MESSAGERESOURCEFILTER table containing the parameters passed here.
     *
     * @param userId the userId of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @return the userID which is also the assigned Id for the newly created record.
     * @throws MessageResourceSaveException on failure to save.  
     */
    public Long createAndStoreMessageResourceFilter(MessageResourceFilter messageResourceFilter, Long userId)
        throws MessageResourceSaveException;
    
    
    /**
     * Updates an existing entry in the MESSAGERESOURCEFILTER table and associated tables 
     * containing the parameters passed here. If the entry denoted by the userID does not exist then one is created.
     *	
     * @param userId the userId of the currently logged in user, this can be retrieved from the session.
     * This value must be set for auditing purposes.
     * @throws MessageResourceSaveException if there is an issue populating or saving the updated object
     * @throws AuthorisationException if the user is not authorised to update the object
     * @throws InvalidUserIDException if the userID passed as parameter is not valid
     */
    public Long updateMessageResourceFilter(MessageResourceFilter messageResourceFilter, Long userId)
        throws MessageResourceLoadException, MessageResourceSaveException, AuthorisationException, InvalidUserIDException;
    

	/**
	 * Translates the referenceId type properties into the locale specific text for display on the front-end.
	 * @param messageResource the dto object to be updated with the locale specific translations
	 * @param locale the Locale to be displayed
	 * @return the same MessageResource object but with the locale translation fields populated with the message
	 * that is relevant to the current locale
	 */    
    public MessageResource translateReferenceValues(MessageResource messageResource, Locale locale);
    
	/**
	 * Translates the referenceId type properties into the locale specific text for display on the front-end.
	 * @param messageResourceList the dto object to be updated with the locale specific translations
	 * @param locale the Locale to be displayed
	 */    
    public List<MessageResource> translateReferenceValues(List<MessageResource> messageResourceList, Locale locale);
    
	
    
}    
